<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE revue[
<!ELEMENT revue (metadonnees,rubrique*)>
<!ELEMENT metadonnees (numero,date,ark) >
<!ELEMENT numero (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ark (#PCDATA)>
<!ELEMENT rubrique (type+,langue+,chronique*,titre+,texte+,auteur+,compositeur*,traducteur*,origine*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST langue lan (cos|fra|ita) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT compositeur (#PCDATA)>
<!ELEMENT traducteur (#PCDATA)>
<!ELEMENT chronique (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
]>

<revue>
    <metadonnees>
        <numero>190</numero>
        <date>1925-02-08</date>
        <ark>bpt6k1330783d</ark>
    </metadonnees>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>Si va di peghiu in megliu !</titre>
        <texte>Si e. buggie ch' elli ci contanù sò vere c'è a sperà chi a 
        Corsica intrarà prestu in la
        Sucità di e Nazione. |
        Caitucoli, sapendu par. esperienza ch'in la nostra tarra fiuriscenu ancui manichi di e
        spazzure ci manda intantu 600
        milioni chi li sò stati. prumessi
        da :Herr1iot.
        Semu pérsuasi chi sta bagattella un tardarà a ghiugne parchi nò cumencimu a mette i.
        boi in lu solcu.
        Ci sò chi contanu pocu in la
        parolla di Caitucoli! Alò alò,.
        chii raprisintanti di a Corsica
        "hanu sempre fattu u so duvere Ì
        e sò degni di tutta a nostra cunfidanza.
        È vera chi à Francia ha di li
        guai a alzà qualchi petra in li
        dipartimenti chi sò stati lavurati da e bombe prussiane, ma
        quandu si tratta di a Corsica
        semu sempre au primu rangu.
        Si Caitucoli dumanda un’
        imprestu. ancu di 600 -miliarde |
        u guveinu farà un sacrifiziu
        ma e li pristarà : cume quandu
        Aprile pristò i tre ghiorni a.
        Marzu par castigà. u picuraghiu.
        Uncertu Licciolu di Guagnu
        avia suminatu i so soldi ind'un
        _chiosu cridendu ch'elli nascissinu !
        Si. Caitucoli tocca i primi
        6oo milioni un c'è a teme ch'ellu i sumenga in li chiosi. I ci |
        darà a poc'a pocu, ma sò sicuri.
        Grazia a l'amore chi st'omu
        porta a la Corsica, prestu avarrém'una cumissione di 22 duttori chi venenu a visità u 'nostru spidale pienu d'infermi.
        Caitucoli è partitu u primu
        a fa cunferenze in li -Cinémas
        di Nizza, di Tilò e di Marseglia.
        A le camaré ‘sò tutti muti
        cume i pesci; a u cinéma, duva nimu parla, diventanu oratori ancu 1 diputati di a Corsica ! Si nò i pudiamu ingaggià im
        lu cinéma a fà i minguli cume
        e scimie ne tirariamu forze
        qualchi prufittu.
        C'è ancu nutizie ancu più
        bone : prestu s'apraranu in tutti
        ! stazzi di a Corsica scole prufissiunale e senza paga.
        Tutte l’arte saranu insignate:
        bancalari, scarpari,rulughiari,
        Tutinari, stazzunari, _ sartori,
        muratori, pittori, scultori ecc.. |
        Ci sarà ancu :
        L'arte di Michelassu
        Manghià, beie
        È andà a spassu.
        Furtunati i zitelli ch'andaranu a se scole ! Saranu cume
        i sculari di u povaru Stantareldi scola 
        a. Marseglia.
        lu ch'in trent'anni
        avianu imparat'a-fa i bastoni [.
        e torti a sera. . a
        ma eranu sempre dritti a.mane.
        LU ultima raprisintazione d dia
        truppa Caitucoli-ha avutu locu.
        L'oratore di:u.
        cinéma ha messu in scéna tutti i battelli di Fraissinet cu l'im- in casa chiulerdu è finitu o u [
        di Bastia, degni d'amirazione più to
        piegati, senza diminticà quelli
        so amabilità versu i passageri
        ghiacari 1 in sacristia. _
        I nostri cumpatriotti di Nizza, di Tilò e. di Marseglia hanu
        purtatu-in trionfu. sta tiova
        Pruvideriza di a Corsica chi
        dopu avè cupartu a tarrà di
        milioni ci prumette una flotta
        cutidiana da purtà-da mare in
        là tutti i nostri prudotti ! |
        Quelli chi. semu ristati in
        Corsica un avemu mancu
        l'anore di vede l'omi a. w:--quale u nostru paésé sarà chiamatu
        à alzà a statua di a Ricunniscenza.
        Quelli chi sò in lu Cuntinente, tra 1 quali molti hanu
        persu a Corsica di vista, sò cun- 1];
        sultati sopra 1 prugetti di U sciò.
        Caitucoli I
        L'ultimu a dà u so avisu sarà.
        Fraissinet, ma quellu vidarete_ ch'ellu incantarà 1 varmi
        a tutti.</texte>
        <auteur>U Monacu</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="fra">fra</langue>
        <titre>LES CORSES, LE COFFRE ET LA CLEF</titre>
        <texte>le fonctionnaire ! Telle est, en
        deux mots, l'impression pel
        t.o vè
        malheureuse Corse se. trouve.
        plongée. | na |
        Or VOYONS : Un ciè più topi
        Ne. con fondons. pas. ci
        Et puis, ditesemot,
        produirait-il SI démain; comme- par enchantement, le. sai
        du miracle. déversait sur les
        côtes de Corse et tous les « jufeux» de l’armée française et
        tous les chefs. de chambrée et|.
        tous les douaniers et fous. Îes
        premiers canards » à quatorze ans de service et r iùstituteur? . |
        Autant de bràs, me. direzVOUS. u
        Oui, dest viai. |
        bras. . croisés.! Di
        Autres bétes affamées que la
        autant de
        Corse riche — ne pourrai
        nourrir.
        . Car, qu'entendez-vous par
        Corse riche ? |
        Personnellement, je me la
        [ma faute, c'est la tienne, t'est
        représente, cette Corse si riche,
        comme .un vaste coffre « bourré» de provisions mais. here
        | métiquement clos; ét devant le|
        quel les corses résignés, atten   
        «Le beli, le “ii si s'i ai
        il déserté !
        grand. nombre d'articles com| |mentant.et déplorant la situation.miséreuse dans laquelle i la
        que SEN
        dent patiemment la distributron de'la becquée.
        Certains, las d'attendre, ont
        > gi
        Ils ont bien fait!
        Si, de ce fait, leur bonheur
        ne s'est pas considérablement
        [accru,leur dignité personnelle n'en esi pasamoindrie d'un
        pouce. :
        Que blôme4-vous ? — PlaiLt sachez bien que lenombre de déserieurs grossira à
        vue d'œil ‘tant que. le coffre
        n ouvrira pas son ventre.
        Mais la clef ?
        La chef ? ? 2... C'est un mil-|.
        liard !
        Un milliard que nous ne
        devons pas. mendier!
        Un milliard qui nous est dii,
        que nous avons d'agni i pair trop
        concessions...et de sang versé !
        Maintenant, si ceux qui tienment le cordon de la bourse
        peuvent — imbunément — — afest vide... et les Corses repus
        et insatiables, tant pis pour
        | NOUS. .
        Ilne nous esi rendu que « la
        monnaie de la pièce»: c'est
        notre faute è tous; fonctionnaires 0u non! .
        Le jour où les intérêts de
        la Corse seront défendus, le
        jour où la juste cause sera
        plaidée par des Corses convaincus etdécidés— ilyena!—
        capables le. cas échéant, — a
        tout risque ! — de signifier àu
        charlatanismé éhonté àue méme la violence est une -côrde
        à larc...ce jouralà le milliard
        Serà « craché ».
        Pas. avant !
        Ainsi done, tant que les Cor- |
        ses persisteront dans leur at‘titude, coupable envers eux-mémes ; tant qu'ils s'obstineront
        à se faire représenter, à représenter leurs droits et leur
        misère par des gens sans aveu,
        le coffre archi-plein s'obstinera à bouder devant... leur
        ventre creux !</texte>
        <auteur>A.F. Tristani</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="cos">cos</langue>
        <titre>LETTARA DA AIACCIU</titre>
        <texte>Caru "Cumpare,
        È un pizzone ch'e' un aghiu intuppatu u portapenna e frisgincatu un pizzacciu di carta, ma chi bulete
        ch'aghiu avutu tantu da fà !
        Mi sò ancu guastu u sangue parchi un c'è statu mezzu di mettesi in
        posta sott'a l'alive cu queilu sulione
        chi tratinia merule e torduli bersi
        l'alture duva l'albitri lacanu spincciulià, sin'à l'intrata di farraghiu, i
        so baghi rossi cume fraule matureé.
        ~ È pò aghiu fattu un giru pa su
        cuntinente. Mi sò coltu, un ghiòvi
        sera, nant'u battellu di Nizza. Mare
        d'ôliu e aria sirena. |
        A bordu c'era l'amicu Chiappini,
        quellu duttore di ceppu anticu,cunsiglierè ginarale di Vicu, òmu d'arte e di scenza tant'amatu e tantu
        stimatu in la. pruvincia a più corsa
        di Corsica. .
        Un sapete chi su medic’ha e manu fatate ? Surtitu da e. prime scòle .
        e da i primi spidali di Francia,è natù cu u so mistiere in corpu, chiu
        babbu, Uu missiau, l'arcimissiau, i
        zii, tutt'u razzinu ! ebbenu par distinu di curà- i so paisani. Ni
        A-ricunniscenza mi forza a cuntabbi a grazia ch'e' devu a so ziu, u
        prete chi accuncciava l'osse cume.
        Agustu di a Cittatella i impiccicava i
        santi di jesgiu. ee madonne di purzillana.
        Mi tocca a palisabbi, o cumpà, chi
        da giovanu era u prima sgaibbissu di u paese. Eiu un mine rameutu ma m'hanu contu ch’e’ ne aghiu
        fattu quant'e Ciccivè. Sempre infantamatu, sempre circhendu stuzzica, aghiu sciaccatu più cazzoti e
        mi sò buscu più sgrignotti ca ch'ellun c'è scope in la Cuma.
        Adunque avianov'anni quand'ellu
        m'accadì un accidénte. D: quella
        sciagura mi n'arricordu cume s'ella
        fussi stalbata dui' etime fà.
        A' ricriazione di à scòla, m'era:
        appiecatu a l'ànnelli duv'ell'ùn s’ab‘bicinavanu ca i giuvanotti chi si
        sintianu spuntà u pelu mortu sott'a
        u nasu. C'era quellu jornu :. Luici di
        Tassu, Matteu di Roccu u sciancu,
        Ghiuvan di Minnia, Buttiglione,
        Ghiaseppu di Ragazzu,. Santu di
        _,. Chilgu, Petru di Midoru, Filippone
        e altri zitilloni.
        _ picinu, i quattru maestri : Borros; Anghiul'Antone, sempre inciaparatu da a narbosa ; Fieschi u Rinnese, c'una mazzetta di frassu in
        manu e Ceccu di Larisciu- cu a so
        barbetta pinzutasi tiravanu dui passi.
        — Mì a Cardiccia.! fece un zurlone indignatu di vede un-muccicosu
        arrampicatu a quell'anelli rispittati.
        E mi dede una puntata. L'altri
        junsenu ad'aiutallu. Mi messi a- briunà, ma, aibò ! A ogni sullivata mi
        paria di francà e fumagliôle di a
        casa di Casgiaghia.
        : A la fine, l’anelli mi sguilledenu
        da e mane e, sfrumbulatu a trenta
        passi, caschedu, parendumi cù u
        bracciu mancu.
        Mi strascinonu in casa sturdulitu ;
        quand'e' ripigliedu u mè spiritu, un
        dulore acutu mi brusgiava u polsu
        chi si ne spincciulava cume un ficu
        maturu.
        Quandi u duttore junse e ch'ellu
        disse chi l'ossu éra troncu, babbu
        parlò di' strangulà i stitutori e pò,
        messusi a u purtellu, dede una. voce a Ghiacumu u Curtinese, u nostru cocher, chi a si pusava nantu a
        paratina di u ponte.
        Quellu, una stundarella dòpu, era
        in piazza cu a calescia attaccata a
        duie stanghe cu Coco, un cavallu
        di sangue, avendu a fiancu a Muschettu e a Hercule, dui arcimuli
        balanini furzuti cume bòi casinchesi
        e ligeri cume muvroni.
        Mi colsenu cu mamma in bittura
        e ne pigliedemu per quellu Fundale
        a galoppu arrabbiatu, a frusta di
        Jacumu fiscava cume una sarpe e
        schricchittava cume un fulmine.
        Franchedemu a Grassacoda, ci
        barchedemu u Punticellu di a Pila a
        Balatrone, etre arche di Belfioree,
        in quattr'e tre sette, ghiunsemu a
        Murzu. ,
        Firmata a vittura, Ghiacumu saltò da' so panchetta, mi pigliò in
        collu e mi purtò ind'una casa duva una vicchiarella, au tintennu
        di e sunaglie, s'era affaccata nant a
        u mutale c'una lumera in manu.
        _ Intredemu ind'un salottu ammubulatu d'una vinttena di carreghe
        e d'una tavula lungaruta. |
        Sopr'a un brancale, ùn Chiglianese chi s'era troncu una jambacaschendu dà una fica, tirava Madonne e Sacramenti. Dui òmi li fecenu francà a porta.; sintesenu uni
        poghi di cricchenni, un Cristacciu !
        un scusate, o sgiò curà, e u stroppiu, addirizzatu, si ne surtì nant'a u
        so brancale cu un surrisu di benistà chi li fiuriscià u sguardu. |
        Quì pò, o cumpà, a ramintizia
        mi face frighie e vembre, ma, postu ch'e'aghiu principiatu, mi tocca
        a cuntabbi l'affare sanu sanu. _
        Isciutu ch'ellu fù u Chiglianese,
        mi purtonu ind'una stanza e m'allungonu nant'a un tavulinu. U duttore, c'èa dì prete Chiappini, un |
        sarcédotte magru e sfilancciatu, ca_— pelli biancu, cu una faccia sperta
        di sapiente e cu dui occhi di culatu, mi pigliò a manu e mi tastò
        u polsu...
        — Un è nulla, disse par dammi
        curaggiu. a |
        E alistéssu tempu mi stinzzò u
        ditu mignulu chi mi parse di sentemi strappà e carne.
        Mulledu un stridu, mà u curatu
        mi sbultava adighià u pollice. Un
        zirlu fù a me prutesta; ellu, cu
        à Calma, mi traia i diti tutt'in seme.
        U supliziu, o cumpà, fù crudele
        ma cortu. Quandi l'ossu si truvò
        apparinatu, a vicchiarella junse cu
        un bollu duv'ell'avia sbattutu uni
        pochi di toruli d'òvu.
        U medicu-sacerdote ciuttò dèntru quella tazzôna un pallottu di
        stoppà, u cacciò cunditu di giallu
        e mi ne ingutuppò u bracciu da a
        palma di a manu fin'au jovitu.
        Tandu pigliò una ferula piaghjnca, a sfittòin quattru pezzi, e, cu
        quelle taulittelle, mi messe u polsu
        cume in d'una cascia, e pò leia e
        chi ti leia.
        E cusì mi ne vultedu in Bigu; mi
        paria di strascinà, appitticatu a'
        spalla, un lonzu di centu libre e
        più. |
        A nuttata, o cumpà, a passedu
        in li turmenti. Mi paria chi tutt'i
        farri rossi di Pistulinu mi tafunissinu e carne.
        Mamma, babbu e me fratelli pusavanu in tond'a u lettu cu tutt'a
        jente di casa ; c'era Anghiula Maria
        a Jrulatinca, Rusavetta di Nesa,
        Saveria di Juvannaccione e zia Ju- |
        vanna cu Marta di Sciarappulellu.
        _Franu cullati i vicini : zia Maria
        di Niscigone cu Marianna e Maria
        Francesca e ancu Matteu, ajutante
        di zuavi in permissione.
        Quella sera, u pianuforte di a
        Signora Cecca, chi da pòi usicondu imperu sgranava arie sintimintale da l'apullà di e jalline a
        l'ultimu picchiu di mezza notte, si
        firmò mutu.
        Ed eiu mi turcia nantu a me stra. punta.
        — Li bolle l'ossu, facia. Marta
        Sciocca.
        — Li bolle, rispundia in coru l'assistenza.
        Allòra, in un sugnacciu, mi paria di vede u me bracciu chi si spulpava e ballava a manfarina ind'un
        paghiòlu, sopr'a un fucône imbabbatu. |
        A mane, u dulore si n'andò in
        fume cu l'alba. Mi ne falaiu sin'a
        u Ponte, più fiierue più sticchitu
        ca un firitu di guerra, -cu_ un mandigliulone biancu annudat'a zippa
        di u collu chi mi pindia da nanzu
        e indun'è punia a me manu cu orgogliu.
        Ottu jorni dòpu a mi pruvava
        a i cazzotti cu Martin di Chilgu e
        Ghiuvanni di a Panittera, chi mi
        purtavanu un annu e quattru dite,
        e m'accadià ancu di vinceli.
        Eccu ciò ch'e'devu a prete Chiappini.
        Ma, chi diamine! quant'e'aghiu
        scrittu senza dì nulla!
        Un c'è più tempu di cuntabbi nulla chi zZrinnighellu ha da fiscà frà
        dece minute.
        _L'Etima chi bene bi parlaraghiu
        di u me viaghiu a u cuntinente.
        Curatevi su ditu ; mittite un battaglinu asa Campanella e scialateavi.
        Bi salutu di còre.</texte>
        <auteur>P. di B.</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>A L'AMICU PUETA TRISTANI, PE' I SÒ « PESCI FRITTI »</titre>
        <texte>Site un cucinaru estrosu,
        E b'intendite in cundime.
        Pè su piattu deliziosu
        B'inviu in ste magre rime
        Centu e più sciaccamanate
        Di saluti accumpagnate.
        S'imbece d'i « Pesci fritti »
        N'era juntu un casgiu vecchju,
        Eo un l'averebbe fattu,
        Puru che mi fussi tecchju,
        Che un ringraziu d'usanza
        A nome di la miò panza.
        Fussi statu puru aschese
        E tamant'a una lughietta,
        Ch'iò n'avessi per un mese,
        A vi dicu franca e schietta,
        C'averebbe scrittu a pena
        Un « merci» pè u tappa-cena.
        Ma,ò Tristà, i vostri mazerdi
        Hanu per mealtru savore...
        Un può esse ch'a i basterdi'
        Ch'un piaqui su bell'odore;
        A me, su pisciame frittu
        Mi sustene l'appitittu.
        Mi sò ghjunti atempu e calli,
        Fumavanu sempre un pocu;
        Sò tutti innorati e gialli
        E rossi cume lu fòcu,
        A bedeli, chi nedite?
        Mi ne leccu labbre e dite.
        Cum'averete pò fattu
        A riesce sa pietanza ? ...
        Site pròpiu justu, esattu...
        E'ùn dicu manc'abbastanza —
        Vostra mudestia — ghj'è intesa —
        Speru, un si truverà offesa.
        L'aghiu compi e pur ne resta, .
        È mai finisceranu.
        Mi n'enzanu a rompi-testa,
        Tutt'e sere pianu pianu.
        Tròvu ch'elli sò savuriti
        Ma... pivarosi e saliti !...
        “
        È bera che quessa un nuce
        A lu savore ch'ell'hanu, '
        Cume un sole a salza Îuce,
        E si sente da luntanu
        ' Di sa.roba, s'indduvina,
        Ghj'è a mòdu corsu a cucina !
        Da si Pesci Fritti s'alza,
        Arditu, un callu profume.
        Ma sa vecchja nuda e scalza,
        A mezz'a l'amare scume,
        Ghj'è quella chi punghje u còre
        Cu e so spine di dulore !!
        U-27-1-25</texte>
        <auteur>P. Borghetti</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>U RIFATICCIU</titre>
        <texte>Spellati un ricciu,
        Mettilu sbrettu
        Un serà mai
        Par' d'un caprettu :
        Or, cusì, sai...
        D'u rifaticciu !</texte>
        <auteur>A. F. TRISTANI</auteur>
    </rubrique>
    <rubrique>
        <type>reprise de publication</type>
        <langue lan="ita">ita</langue>
        <titre>MAZZINI È LA CORSICA</titre>
        <texte>La Revue de la Corse, chiedeva,
        tempo fa, ragione del viaggio fatto
        da Mazzini in Corsica nel 1831:
        non’ è difficile dare la risposta. Tutti i biografi del grande genovese ne
        parlano, e Mazzini stesso ne scrisse ampiamente nelle sue Memorie
        autobiografiche. (Scritti editi ed inediti. Vol I, Milano, 1861, pag. 48).
        Liberato dal carcere di Savona ed
        esigliato dagli Stati Sardi, si era
        recato dapprima:a Ginevra, ove aveva conosciuto -personalmente lo storico Sismondi, indi era passato a
        Lione, centro importante  dell'emigrazione italiana in Francia. Quivi
        si preparava col tacito consenso del
        Governo una spedizione di elementi.
        rivoluzionari italiani e francesi in
        Piemonte, onde proclamarvi l’insurrezione. Se nonchè all’ultimo momento l’impresa che doveva. iniziarsi
        a traverso la Savoia non ebbe più
        luogo per la .caduta del ministro
        Laffite : Casimir Perier che gli succedette, non volendo avere noje con
        l'Austria e con la. Sardegna, impedi
        con. la forza ogni tentativo in proposito (febbraio 1831). Mazzini, il
        quale naturalmente doveva anch'egli
        parteciparvi, rimase assai deluso ed
        irritato da questo tradimento di Luigi Filippo, portato al trono da una
        rivoluzione liberale. - _
        Mentre i numerosi - profughi discu‘tevano sul da farsi, . qualcheduno
        -propose di recarsi in Corsica e di
        là nelle Romägne à prestare man
        forte all'insurrezione ivi scoppiata. Il
        progetto ardimentoso venne senz'altro
        accettato, e si decise di partire subito. Mazzini, ebbe a compagni di viaggio Borso de’ Carminati, Voarino,
        Carlo Bianco, Tedeschi, Zuppi, ed
        altri patriotti, già compromessi in moti insurrezionali precedenti.
        La Comitiva, non avendo trovato
        a Marsiglia nessun bastimento in partenza per l’isola, si diresse. verso
        ‘Tolone, ove, malgrado un mare tempestosissimo, preso imbarco su di un
        legno napoletano giungeva a Bastia,
        dopo una traversata delle più burrasc ose. _ |
        Nella piccola. città non mancavano
        esuli: vi incontrò un certo Nicola
        Ricciotti di Frosinone e moltissimi
        | altri, quasi tutti peraltro in cattive
        condizioni finanziarie. La Carbone
        ria era fiorente nell'isola; vi era stata’ introdotta dapprima dai militari
        stati al servizio di Giuseppe Bonaparte e di Murat, entrambi Re di
        Napoli, poi dai. profughi napoletani
        della rivoluzione del 1820. Tutta la
        Corsica era un- centro cospiratorio
        italiano attivissimo. Anche i« Pinnu| ti è società segrete locale, aveva molti
        | aderenti. A questesocietà appartenevano Pietro Bonaparte, Pietri, il futuro
        | prefetto di polizia di Napoleone III, il
        Principe Baciocchi, futuro ciambellano
        imperiale e moltissimi elementi bonapartisti.
        «La Carboneria; ‘scrisse Mazzini,
        era allora dominatrice dell’isola e i
        popolani ne facevano quel che ogni
        uomo dovrebbe fare -d’una associazione liberamente accettata, una specie. di religione »,
        Ne era capo venerato un certo
        Gallotti,. napoletano ; grande impulso
        vi avevano pure dato un vecchio
        prete di nome Bonardi antico affigliato di Buonarotti, e il La Cecilia,
        il quale ultimo, aveva fondato negli
        anni antecedenti parecchie vendite.
        Questi con la tolleranza del prefetto
        Jourdan, aveva organizzato una ventina di compagnie di corsi completamente equipaggiate, pronte a scendere in Italia in caso d'insùrrezione,
        Erano circa duemila uomini, -guidat: da ufficiali della Guardia- Nazionale, il cui servizio in Corsica,
        al dir del Mazzini, era assai più duro ed attivo che altrove, Il Comitato già prima ancora dell’arrivo di lui
        aveva mandato al Governo Provviso
        rio di Bologna due delegati, Santelli
        e Matteucci, a offrirel'aiuto di queste giovani ed ardite falangi, e domandare soccorsi finanziari. Poichè
        se non facevano diffeto le armi ele
        munizioni, mancava però il denaro,
        per il noleggio dei legni necessari
        al trasporto, e per dare un lieve sussidio alle famiglie povere degli isolani che dovevano partecipare all’impresa.
        | I nuovi arrivati, impazienti d'una
        risposta, inviarono a Bologna, altri
        Antonio - Benci,
        due delegati, certi Zuppi e Vantini,
        a sollecitare una decisione dal Governo bolognese. Ma questi che sperava solo il trionfo della propria causa dal non intervento, proclamato
        dal Gabinetto di Luiggi Filippo, contro le armi austriache, temute dalle
        popolazioni assai più di quelle pontificie, declinò ogni proposta di concorso esterno. Così « d’indugio in
        indugio ”, gli austriaci, noncuranti
        delle minaccie francesi, avevano
        invaso le Romagne, nella prima
        metà di marzo, ed occupato Bologna
        il- 21, mentre il Governo Provvisorio
        si rifugiava in Ancona. |
        Svanita ogni speranza di un efficace
        aiuto all'insurrezione, specialmente
        dopo l'infausta giornata di Rimini, e
        la capitolazione di Ancona, avvenuta il
        27, non rimaneva a Mazzini,che di ritornare in Francia con gli amici.
        Giunto in Corsica nella prima metà di
        marzo, nè ripartiva verso la fine dello
        stesso mese, diretto a "Marsiglia.
        Del suo soggiorno nell'isola lasciò
        scritto molti anni dopo : «Là mi sentii nuovamente con la gioia di chi
        rimpatria, in terra italiana. Non so
        che cosa abbiano fatto dell’isola,
        d'allora in poi, l'insistenza corruttrice |:
        francese e la colpevole noncuranza
        dei Governi d’Italia: ma nel 1831
        l'isola era italiana, davverro italiana non
        solo per aere, natura e favella, ma per
        tendenze e spiriti generosi di patria. La
        Francia v'era accampata. Da Bastia e
        ‘Ajaccioin fuori, dove l'impiegatume era
        di chi lo pagava, ogni uomo si diceva |
        «d’Italia, seguiva con palpito i moti del
        Centro e anelava a ricongiungersi
        alla Gran Madre. Il centro dell’isola
        dove io feci. una breve corsa, con
        ‘collaboratore dell'Antologia e ricovratosi, per minaccia di persecuzione, in Corsica, guardava unanime ai francesi come a nemici. Quei ruvidi ma buonissimi montanari, armati quasi tutti, non parlavano che di recarsi a combattere
        nelle Romagne'e c'invocavano Capi.
        Leali, ospitali, indipendenti, gelosi
        oltremodo delle loro donne, avidi d’èeguaglianza e sospettosi del forastiero,
        per temenza di violata dignità, ma
        fraterni a chi stende loro la mano
        come d'uomo a uomo, € non come
        d'incivilito a selvaggio, vendicativi ma
        generosaménte e di fronte, a avven| turando nella vendetta la vita, quei
        Corsi mi sono tuttavia un ricordo
        d'affetto e di speranza ch'essi non saranno sempre divelti da noi ».
        Giunto a Marsiglia, riprendendo un
        ‘disegno maturato nella solitudine del
        carcere di Savona, egli fondava la
        Società « Giovane Italia », al cui
        paragrafo secondo, leggesi, «che le
        isole dichiarate italiane dalla favella
        e dagli abitanti nativi» dovevano fare parte dell'Italia unita. Da questo
        momento la Corsica, ebbe nella chiave del cifrario segreto mazziniano il
        N. 9 ( Famiglia Corsa). _
        La fallita insurrezione dell’Italia
        Centrale, per il voltafaccia di Luiggi
        Filippo e dei suoi ministri, gli ispirò
        Il famoso. articolo : “ Una notte di Rimini » scritto in francese e publicato
        nel Nafiona!, di Armando Carrel, ed
        in italiano (in due edizioni pressochè
        uguali ) dallo stampatore Fabiani, di
        Bastia.
        'L'isola ne] frattempo, data la reazione imperversante in tutta l'Italia,
        erasi . riempita di esuli scampati alla
        prigione ed alla forca.
        Mazzini non ritornò più in Corsica,
        ma alla Corsica pensò lungamente,
        come resulta dal suo voluminoso epistolario, il quale purtroppo non è an(cora intieramente publicato.
        E conservò rapporti cordiali con molti patriotti corsi, e coi profughi italiani
        viventi nell’isola, fra i quali ultimi sono
        da ricordarsi Murciano, Vecchiarelli,
        Iliani, Berghini, Guittera, Castelli, Argenti, ecc. Fu in relazioni epistolari, 0
        personali, con Luigi Napoleone, futuro
        Napoleone Ill, col principe di Canino,
        con Gerolamo Bonaparte, tutti allora
        republicani. Fra i corsi figura frà i suoi
        aderenti un Pietro Francesco Roccaserra, di Sartena (?) « ottimo giovane »
        sebbene un po' ciarliero, il quale nel
        1833, gli offerse una legione di ottomila
        corsi per sollevare l’Italia Centrale,
        Mazzini ci credeva poco ed esponeva i
        suoi dubbi a Melegari, al quale aveva
        poco prima chiesto notizia di un lavoro
        d'argomento corso « Anna d'Ornano »,
        del quale ignorava il nome dell’autore.
        me ————————__
        Nello stesso anno, in una lettera del
        settembre, a Francesco Franchini, corso, del quale aveva molta Stima, conveniva sulla utilità di gettare una ban.
        da di corsi nel golfo (di Genova ?) sola.
        mente però, a coseincominciate altrove,
        Intanto s'interessava alla «Storia della
        Corsica » del Jacobi, ed a Pietro Giannone, a Parigi, domandava quale uomo
        fosse l’autore, e ricordava con nostalgia
        il mare di Corsica.
        Nel 1843, l'esule napoletano Giusep.
        pe Ricciardi, vagheggiava uno sbarco
        di corsi nello Stato Pontificio, quando
        vi fosse scoppiato qualche moto. Reca- :
        tosi nell'isola, salvo errore assieme al
        romano -Pietro. Sterbini, si era incon.
        trato con Alessandro Cipriani, fratello
        di Leonetto, col medico Atanasio Basetti, di Vairo (Parma) proscritto del
        1831, con Oreste Biancoli, con Giovanni Righi Lambertini, coi fratelli Muratori e con Giuseppe Lamberti. Ma il
        suo progetto non aveva incontrato. che
        scarsi consensi. Mazzini stesso non aveva molta fiducia nella riuscita di un
        piano simile tanto più che proprio allora il prefetto della Corsica aveva negato lo sbarco a Bastia a diversi profughi,
        Nicola Fabrizi, che da Malta, voleva
        egli pure recarsi: néll’isola, dovette rinunziare a questo suo proposito, -dato
        ‘anche che il Governo francese era stato
        messo sull'avviso di quanto ivi si tramava, dal Nunzio Papale.
        La disgraziata spedizione dei Fratelli
        Bandiera nelle Calabrie, finita tragica.