<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE revue[
<!ELEMENT revue (metadonnees,rubrique*)>
<!ELEMENT metadonnees (numero,date,ark) >
<!ELEMENT numero (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ark (#PCDATA)>
<!ELEMENT rubrique (type+,langue+,chronique*,titre+,texte+,auteur+,compositeur*,traducteur*,origine*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST langue lan (cos|fra|ita) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT compositeur (#PCDATA)>
<!ELEMENT traducteur (#PCDATA)>
<!ELEMENT chronique (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
]>

<revue>
    <metadonnees>
        <numero>198</numero>
        <date>1925-04-05</date>
        <ark>bpt6k1330791z</ark>
    </metadonnees>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>BABBU DI A PATRIA</titre>
        <texte>Chi bellu Nome! Stu. Nome d'oru u Pòpulu
            còrsu — pòpulu liberu, unitu
            e cungregatu — in segnu d'alta ricuniscenza; l'ha datu a'un
            C'òrsu... |
            _— Stu Còrsu è u più grande
            ‘di i veri Còrsi!
            U “più grande 1 un fù, nè
            "Sambucucciu di Alandu, nè
            Sampieru di Bastelica, nè
            marcu N apulione . !I Nò ! man-.
            "cu Napulione !..Perchì quellu,
            "natu Còrsu fù un Cesare francese rinegätore di FIdea còrsà,
            4 primu lume di i. so vint'an' - ni.
            
            U più gràndè di: i nostri è
            ue Paoli, # figliòlu d'un
            Paisanu di Castagniccia, natu, ingrendatu, fi fiuritu e sfi u
            | ritu e interratu in terra cèrsa.
            Paoli | è l'Ala di a nostra
            | _Sterpa,. TY Ala gloriosa chi sulleva all'aria Panima d'un pòpulu eroicu pregna di virtù
            rumana.
            C'una palla. rossa, u distinu
            ladru li truncò u volu. |
            D'un. colpu di falcione u
            _— Furzutu diccennullò e speranze pronte à spigà:
            Ma fin ch'èllu c'è fiatu ritreghi ianu Paire di esacre speranZe.
            ‘te cantavanu, cu l'acelli, nan"tu: i: pulloni- chì adombranu
            "Merusaglia. À quellu cantu
            spuntò un fiore, u figiòlu di IaU cinque d aprile 1725, V’au-Fieri diu nostru passatu,ascullemu à voce parlante di u
            so epitafiu:
            I1- padre dellà Patria è qui sepolto u
            © La dove nacque ei giace ©
            * 1] pio voto di Cirno è sciolto
            * Requiescat in pace.</texte>
        <auteur>Prete Carlotti</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>De Paoli eu Pueta</titre>
        <texte>_ Quandi u pueta corsu picchiò a la porta di u paradisu, Pasquale de' Paoli, u babbu dia nostra patria, li sbaJlangò l’intrata-re pò li disse:
            Qui si canta ogni sera *« Eternu cantu »
            Par prighera si dice « A Muntagnòla, »
            Ma conta : è bera chi fra guai è piantu,
            Cirnea si trov'abbandunata. è sòla ?
            Cumu stà Corti ? e Bastià ?ed Ajacciu ?
            Allòra u pueta, stancu. d'avè cantatu. nù Vanu, aprì a so
            brisacca. e. cacciò i scritti di1
            | patriotti. : :
            A prima fu «A Muvra »]
            chi cu e so corne ha datul
            da corte. a tanti bastardi, a ve-,
            ta chi sona u cornu di a:Li-1
            bertà ; da tantu ch'ell'è. biasE pò li fece vede l’apostutu, Märtinu Appinzapalu, d’Al-{
            Vieri, Angeli, Paoli di Tagliu, |
            [si più; a majò s'ha magnatu [.
            A castagna face a pena in cor x
            A scòla di a Liberta, di PIn- :
            dipindenza è saîrata; tempu è
            . | ditròva sumirina e di rinchini.
            [litare, a chi corre a .mettesil
            -' Bônarriatàa è di parcittori e Di
            : Avà si vede a volpe annan(t'a i chjrasgi. Ma'ùunu sconciu
            U ritrattu di a Patria è. pes| simu. Ma curaggiu, gridò u
            È bera, à Patria è divintata un stracciu? [
            |
            |faratu una malatia chi vene
            I ratu;
            ~
            timata, u pélu li luce.
            li corsi : Pincu, U Strampalaa
            timonti, Minicale, Nottini, OliLucciardi, e Maistrale, e pò
            tant'altri.
            _ De! Paoli basgiava a tutti
            e di tutti era cuntentu e fieru,
            ma vulia sénte e nutizie, tutte enutizie corse.
            Allòra u pueta li cuntò : i A Patria un esiste guaa chjuca ; ;, a nostra lingua è
            tutta. piéna di pruni. è d'arbaccia frustera ; in più li s'è afda mare inlà.
            U castagnu è distruttu è macillatù e vindutu.par apisentu.
            pu a tutti.
            I paesi si spopuleghianu; a
            chi scappa a purtà u zanu mil'umbasti di l'impiegu...
            : U pilone è persu; a mòda ha
            vultatu u ciarbellu a è donne.
            E raccolte sò bundante di lamaghioni e di prunalbelli; u.
            pane di l'ôrzu, è mortu..e. suttai mulini,
            guardanu. Ur celu e piegneriu..
            di carta bullatà : quessi cresce‘{nucumea rimigna.
            E strade ei stradoni : SI face-.
            {nu, ma.a le cuülunie:.
            - A Francia tene caru u scotia corsu, Pisula; di noialtri |
            sine passa. |
            A roba cumprata è distinata
            a esse vinduta. Vinduti o rigalati saremu 1 da. dumane a a dòpudumane... À nôstra i padi'ona: has morte
            [ apressii; i topi s'hanu quasi
            ruzzicatu a bandera corsa. . face un-acconciu!
            pueta: a sumente è posta e a
            stella luce ! ! |</texte>
        <auteur>Maistrale</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>Un Pelegrinaggiu a Merusaglia.</titre>
        <texte>Mesi scorsi; in Merusaglia,
            Ghiuntu perà occasione,
            A la casa di de Paoli,
            Cun rispettu. e divuzione,
            Pér duvere e per omaggiu,
            Ci andéti in pelegrinaggiu.
            Appena frañcatu a ziglia
            Mi sente cummòve u core,
            Pensendu che mi truvava
            In casa di u fundatore
            Di sta Patria tanta amata,
            E sempre più venerata.
            Vidi quelle sale biòte
            Chi mi fecenu pietà;
            E micca, o pochi ricordi
            Cari, ci pobbi truvà.
            _ Da u dulore ché ne sentu
            U miò core sbruccia in pientu.
            Dòpu avè scrittu a u registru
            Sò passatu a la cappella,
            _ Duv'è un bustu di dè Paoli:
            Culà, nant una chiappélla,
            _In dinôcchie mi lampai,
            E pienghiendu li parlai :
            "«Vurrebbe 'sapè. da voi,
            Paoli, cosa pensate
            Di a cundotta di li Corsi
            Versu le côse passate.
            Püderanu esse accusati
            Cùn voi d'esse trôppu ingrati ? ?
            -. Vecu che li scappa u pientu.
            E, colmu d’euzione,
            Face, trinnighendu u capu,
            -Gesti di-Cumpassione.
            S'asciuvà, si spoîga, è dice,
            SÈ Ma cun'eria assai felice :
            «Un crédu ch'abbia da fà.
            C'unà persona impurtuna.
            N emeénu. c'un temerariu,
            Chi, sénza ragiône àlcuna,
            | Tròvi gustu a discitammi
            Nunda che per annuiammi.
            «Di li Corsi ùn mi ne lagnu ;
            Mancu di a so indifferenza,
            Chi nun ghiè, n'aghiu le pròve,
            Che un poëu di négligenza :
            | Dunque un ponu ésse chè amati,
            ~E da mè sempre stimati.
            « Tenenu a'lù so paese, ;
            Ghiè la cosa principale ;
            D'i so antichi ne so fieri,
            E pertuttu in generale,
            E nostre glorie. passate :
            SÒ da ognunu venerate.
            « Schiavi di la so parolla,
            All'amici assai fidati,
            Sò li Corsi tutti apparu *
            Ben'visti e cunsiderati..
            Ciocchi più li face onore,
            LH Certu, e d'esse mi di core.
            U li tròvu più che un difettu
            Chi cuncerna u so parlatu:
            L'ignurenti e li struiti
            A và l'hanu abandunatu ;
            E un si parlà in stu paese,
            Più ne corsu ne francese.
            
            «S'elli mi stessinu a sente,
            In dinocchie i pregheria
            Di parlà cume i so vécchj...
            Sinnò prestu all'agunia
            Cirnu s'ata da truvà,
            Priva d'ogni libertà...
            ‘ a Quelli chi lascia a so lingua.
            Mancu tene a la mamma :.
            Un-ë lu to casu, o Còrsu.”
            Dunque un stà sordua sta chiama,
            E ghiura chi u to parlatu
            Sarà, intattu, cunservatu>
            ‘Li feci un’altra dumanda |
            Chi mi stava. troppu a u core,
            Per sapè cosà pensava
            U nostru legislatore,
            Di quell enime valente
            "Chi sô" th" Gbli sempré érrente_
            Li vecu aggrunzà le. ciglié,
            E un rimproveru m 'aspettu. *.
            Ma, mi disse in sottuvoce,
            Per piettà lu so dispettu :
            « Forse alzaste a tanta glòria. __
            Una croce pet memòria? ?
            Mi sentu. infiarà all'istante
            ' U miò voltu da u russoré.
            Pròvu a. circà: qualchi scusa,
            Ma un ci n'è... Cum'è? Signore!
            Paoli, dund'è pigliatu ?
            Averaghiu sunniatu?
            Forse si, ma .se parolle.
            Sò la pura. verità ; OI,
            ‘ Di un pensà più a i. mostri, Eroi
            Ci duemu vergugnà.
            E dipòi riposu ùn tròvu,
            O Morti di Ponte-Nòvu 1...</texte>
        <auteur>G. P. Lucciardi</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="ita">ita</langue>
        <titre>RITRATTU.</titre>
        <texte>Vissé'sobrio, vi gilante, apéroso.
            Bella é complessa la persona, nè
            curva per gli; anni, che le. conciliavano venerazione ma non ispegnevano la bellezza: la fronte alta pinsosa e sereñd, segno d'ampia mente
            ed onesta; capelli lunghi, sppracci-i
            glia folte, e nell’ aggrottarsi terribili; occhio. ceruleò,
            fino in vecchiaja; sguardo intenso,
            . Severo ‘0° soave come. volesse: la
            forma e l'atto delle labbra indici di
            bontà e di fermezza. Colore chiarò
            e vermiglio; pace nel viso e modes‘tia, e sincera risolutezza, capace di
            maschi risentimenti. Voce sonora,
            piacenté; pronunzia posata, scolpita,
            ‘ trémula nello sdegno. Dignitose le
            manière e cortesi, il gesto rado, celere il pàsso e franco. Vestiva abito
            largo, decente non pomposò, di color verde con oro. Cavalcatore non
            ‘destro: poco sedeva: ammesso talual pensiero.
            no a colloquio, passeggiava seco
            senza parola, per dare e aver tempo
            Nel. parlare brevità
            pronta,:ed. affabile, non - soverchiatricè, come del Buonaparté: dire
            preciso, fine, talvolta eloquente;
            semplice sempre. Nel piglio sicuro
            .e impérioso, autorità da chetare le
            querele ed imporre silenzio. Umore piacevole; .frizzi ingegnosi, ma
            non prurigine di falezie: e diceva
            che il riso nelle cose politiche . denota sciocchezza. Sorrideva, anzi
            che ridere, un sorriso arguto e l'avrei voluto ‘vedere nell’atto ch’elesse .le parole dell'arcade Marat, il
            quale chiamò lui, dico il Paoli,
            homme exiravagant èt sanguindire. L'ingegno. desto, ed ornato, sé
            disadorno lo stile. Sapeva passi d’antichi a mente: sapèva di storia, e
            T'inglese;leggeva il Pope, elo Swift.
            E la sua libreria, per la scelta, era la
            lode dell'uomo. A scrivere. gli si
            rompeva la testa; déttava, e non
            molto. «Io sento, solea dire, non
            ragiono » : ma sentendo, ragionava
            sulla provvidenza di Dio, e sulla
            lingua de’bruti. Discorreva su vari
            soggetti, franco e fondato. E'non.
            sapeva mai il dì del mese; ma il popolo tenevano ch'egli antisapesse il
            futuro.
            Sentì l'ammirazione, la. gratitudine, l'amicizia. Patriota, parente compare, non gli erano nomi vani. Le
            parole amorevoli nelle sue lettere
            son parche, e per questo efficaci,
            sebben trite dall'uso..
            (Lettere di de’ Paoli — Proemio —
            Firenze 1846 )</texte>
        <auteur>Tomaseo</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>Vita di Pasquale de’ Paoli</titre>
        <texte>Nasci Pasquale de Paoli in 1725
            a la Strétta di Merusaglia di Rustiou. U babbu di Pasquale, Ghiacintu, era statu a ucapu di a grand'insurrezzione corsa ma, dòpu a disfatta d'i Corsi da Maillebois, si rittirò
            in Napuli, cu i so dui figliòli Clemente e Pasquale. Fù in sa città,
            inn'u i loghi stessi chi bidenu u
            splendore d'u geniu latinu, chi studiò u giovanu Pasquale.
            A l'epuca ch'ellu studiava, cuminciavanu.a sperghiesi, e famose
            idee di Voltaire, di Rousseau e di
            | Montesquieu, idee chi passate in u
            so cerbellu cirnese, pérseiu tutt'u
            sò velenu, e conservonu tutt'a so
            { bella significazione.
            x
            * * | |
            Elettu ginarale di u regnu di Corsica, Paoli lasciò Napuli per béne
            in Corsica duv’ ellu sbercò u 29
            Aprile 1755A so amministrazione fù maravilione, «'avait réussi à faire renaître
            ali milieu dè la Méditerrannée- les
            beaux .jours de Sparte et d'Athènès. » A* Corsica smaravigliò tutta
            l'Auropa. În ‘un isula cusì chiuca,
            si videnu in 'opara tutte l'istizioni
            d'un regnu ideale : istituzione chi
            mai avanti s'eranu ‘viste altrò. Cunobenu i. Corsi, allòra, ghiustizia,
            struzione, pace e prosperità, cose chi
            l'eranu sempre state tolte.
            * A
            Creò Paoli un Università in Corgliosa. Paôli, cum'ellu dicia Napu-.
            4
            ti; centru di l’Isula. À u capu di a'
            quale messel'òmi più sommi di l'epuca, e pe a quale avia fattu fà un
            pianu minuzioôsu di studj, e d'à manera d'insignà. U scopu di st'Università era di dà a la valurosa e
            studiosa giuventù corsa una direzione patriottica.
            «Incuraggì - l'agricultura,
            strade,
            : fece fà
            fundò l'Isulà Rossa, creò
            unà' muneta naziunale, fundò una
            stamperia e un ghiurnale ; stabilì
            un mulinu a polvara e una fabrica
            d'erme.
            AU puntu di vista murale, calmò
            è numicizie di e famiglie, nimicizie
            chi eranu a piaga di a Corsica.
            * I
            do de
            Ma quand'ellu si sfurzava di dà a
            la so nazione e stituzioni chi servìnù. di mudellu a l'Auropa fu susci-tata un'altra guerra.
            Umiliati di a so disfatta i Genuvesi
            si vultonu versu a Francia e chersenu u so aiutu: A Francia occupò
            u furtezze di San Fiurenzu, Calvi e
            Aisicciu e, pocu dòpu, cumprò a a
            republica ligure i so dritti sopr'a
            Corsica.
            A l’annunciò di tale nutizia; Paoli
            cunvucò una cunsulta generale
            chi dicchiarò, ch'i Corsi, un si lascèrebbenu bende cum’una banda
            di pecure ; tutti patriotti risposenu a
            libertà o a morte! .
            | Æ |
            er
            U marchese di Chauvelin avia,
            appena iuntu, dicchiaratu . ribellu
            tuttu Corsu ch'un si serebbe sottumèssu ala Francia.
            A guerra cuminciò, dòpu a suttumissione di u Capi-Corsu, Chauvelin assaltò in listessu tempu Nebbiu e Marana.
            I Corsi, chi eranu in Loreto, si
            lamponu nantu i Francesi, e i spazzonu d'a Casinca. I patriotti, sott'a
            u cummandu di Clemente Paoli, i
            perseguitonu fin'a Bastia puglienduli prigiuneri e cannoni.
            In Nebbiu u nimicu fù cacciatu
            d'Oletta, è i nostri s'impadiuninu
            di San Fiurenzu, Patrimoniu e Barbaghiu
            .Pasquale Paoli dede ordini a u
            fratelle Clemente d’attacà subitu,
            per cuntene u generale chi occupava
            a strada di Nebbiu.
            I Francesi, chi tinianu a Borgu,
            attacconu tre bolte, ma funu rispinti.
            In ne piezze, in ne cherrughj, e in
            
            ne case, a lotta fù crudele : i battaglioni di Chauvelin funu rotti e polverizzati da e milizié corse. Ste milizie; duve c'eranu ancu preti è
            donne. funu eroiche. Mille e ottu
            centu francese, tra morti. e feriti,
            ristonu nant'u campu di Battaglia.
            A guerniggione. di Borgu cumandatu da de Ludres, Ssi rese, lasciendu
            a i Corsi, sette cente òmi e binti
            cannonni ; a vittòria fù cumpletta,
            Paoli ne a l'onore eternu !
            I Corsi vincitori pruposenu a pace a Choiseul. Per risposta, u minisiru di Francia, "mandò un'altru
            generale, u Conte de Vaux, cun
            nòve truppe. |
            Tandu, :Paoli chiamò a l'ermi,
            tutt'i l'òmi. di sedeci a sessant'anni
            per salvà a Patria.
            Paoli purtò u so quartieru generale in Merusaglia. De Vaux u
            seguitò ! NÒ
            Tre ghiornu l' èrinate si guerdonu
            senz'attaccà. De.. Vaux cuminciò
            l'attaccu ma ddpu ünalotta d itre òre,i Francesi funu rispinti cu perdite,
            Cinque volte, i Corsi i fécenu rinculà, ma a la fine de. Vaux pigliò
            Lentu e Canavaghia. i. . cc.
            . L’oru di a Franciae.i. traditori
            dedenu u colpu mortale a l'indipendenza corsa. I Taliani di l'epuca. haPU
            indicatu i mezzi impiegati pè a cunquista d'a Corsica, cu su disticu
            famosu.
            Gallia vicisli ; profuso turpiter auro.
            Armis pauca, dolo plurima jure nihil.
            chi traduce bè i fatti.
            De Vaux avia accampatu annantu e Custere cu d'Arcambal in Ostriconi e Marbceuf prontu a lampassi
            in Casinca.
            U quertieru generale di Paoli era
            in Rustinu, Clemente Paoli cupria
            abocca di Sant'Antone e i paesi di
            Bisinchi e Pastoreccia, Gaffori era
            n Ponte Leccia.
            ' L'ottu maghiu, i patriotti impazienti di cuminciàa battaglia, collanu fin'a Lentu, in duv'eranu i Francesi,
            ma de Vaux, li si mette appressu.
            L'ala dritta d'i Francesi, stabilita in
            Canavaghia,
            patriotti si voltanu, .ma un pònu
            rissite a la mitraglia pinzuta. Ingutupati fra dui fochi, i patriotti falonu fin'a Pontenòvu per francà. u
            fiume. Ma nant'u u ponte, c'eranu
            i Prussiani. chi sirvianu sott'a Paoli
            cu i miliziani corsi, chi per malintesa, o per furzà quelli chi fughianu
            a tene fermu, tironu sopr'a elli. Malgradu u culunelli Gentili, "u disordine fù spavintosu.
            Da Rescamone Paoli bidé Golu,
            TÒssu di sangue d'i martiri, e a mor:
            te di l'indipendanza, ch'ell'avia vulsutu dà a la Corsica. |
            sE Pasquale de’ Paoli
            _ (stampa populare)
            A cunquista d'u nostru paëse fù
            da su iornu éumpita
            Paoli partì da Corsica u 12 iugnu,
            i769. Quand'ellu sbercò in Livornu,
            cunnobbe: tutt'a simpatia. ehi «un.
            pòpulu italianu ' avia pe i so frattelli
            corsi. Curfia u, pòpulu « quasi frenetico, .or quà, or là per dove,
            dovea passare, nonmai saziandosi
            di vederlo,- denendo acclamato da
            i più sensibili, éd ammirato da i
            più ri iflessivi, e fi inalmente da altri
            compianto per lasua poca furtuna,
            in quest ulmi incontri, avendo dato bastantemente a cunoscere le
            di lui operazioni, quanto ‘aveo
            saputo adoprarsi, der rendere
            libera e culta una naziane stata
            per l'addietro serva e ignorante.»
            D'alfronde, un Sòlu a folla li rese
            st'onòri ma ancu i scrivani italianii
            più grandi di l'epuca : Lorenzu -Pignotti cunsacrò a l'« invitu eroe »
            una magnifica poesia : Vittoriu Alfieri dedicò aux ‘prugandor magnanimo dei Corsi. .» a so tragedia Timoleone.
            Dòpu vint'anni d'esiliu, quandu
            fu permessu a tutt'i patriotti chi
            avianu lasciatu Cirnu dòpu a vittòria francese di rientrà in li so
            rughioni, Paoli partì da Londra induv'ellu s'era ritiratu e si rese in
            Pariggi. Quallà fù _ presentatu ~a
            Luigi sedeci chi li dede u titulu
            di Tenente generale, cu u cummandu
            militare di Corsica.
            
            Ma u iornu u più caru à u Padre
            di à Patria fù u iornu ch'ellu sbercò in Macinaju di Capi- Corsu. Tandù si messe in ghinochie e bagiò a
            terra cirnese tant' amata.
            *
            * *
            Guvernò allòra a Corsica, segondu legge francese, ma su guvernu
            fù cortu, perchè subitu bensénu i
            flagellu di Revoluziône sanguinaria.
            Fu ciochi l'alluntanò da i principj
            revuluziunarj. Preferì dà à Corsica
            a l'Inghliterra chi a guvernò dui
            anni. |
            Dürente a duminazione Inglese,
            Paoli avia duvutu turnà un altra
            volta in esiliu. S era difinitivamente
            ritiratu in Londra in duv'ellu . morse
            u cinque feraghiu. 1807.</texte>
        <auteur> Mattei TORRE</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="ita">ita</langue>
        <titre>Lettera a Cocchi</titre>
        <texte>Mai dunque cesseranno le diffidenzg)
            Credono che possa aver mano per sp,
            toscrivere il contratto della servitù del.
            la mia padria ? Mi credono cosi Poca
            attaccato ed impegnato a sostener quel.
            la forma di governo che è quasi tutta
            mia opera ? Mi credono così poco sen.
            sibile all’atroce ingiuria, fattami, o che
            sia così imbecille di mai confidare nelle
            promesse della Corte di Francia 2.
            Ne'miei scritti, assicurate pure che non". :
            parlo il linguaggio del cuore, ma quello ‘ :
            che conviene alla povera padria, alla
            quale convienne che io temporeggi.
            A me riesce di vieppiù animare il popolo, facendogli vedere che, nôn:ostan.
            te la sincerità delle mie intenzioni per
            la pace. li Fraricesi sono sempre ; duri,
            perchè ci voglionò come pecofe. Arri.
            Isola Rossa, u
            vai al punto che quasi non mi restava.
            più che mio fratello, e non cedei cederò ora che traluce quale he speran,
            za ? Ah, mi credano più onesto o più
            'ambizioso ! Mi. credono d’intelligenza’”
            con i Francesi, rel ‘tempo. che. questi:
            non lasciano mezzo per far privare di
            vita me e mio fratello ; s'insospettiscono perchè tratto bene i prigionieri: ne
            ho le mie ragioni, e dovrebbero essere
            informati del mio modo di pènsare:
            nori sarò mai itumano perrappresaglia,.
            Fra. questi. prigionieri ci ho degli amici
            che ai par de’ zelanti Còrsi detestano. .
            questa guerra. Quando sarete..qui. col
            vostro abito di marinaro, resterete per- .-.
            suaso che io mi regolo bene nella cir:.
            costanza. Il maggior timore. sapete .
            quale è : se i Francesi oonoscono che. -l'Inghilterra voglia prender parte, essi
            | non mancheranno subito di far pañt ©
            larghi, ed asserire di trattar sull’antico .
            _piede, a voi noto. Se io rifiuto, li lor
            partigiani ingrossano il partito : : i buo-.
            ni, se non vedono scoperta e dichîaratà |
            PInghilterra, dirannô sempre : ma:cosa .
            volete aspettare? ci offrono i Presidi, |
            ci vogliono riconoscere. liberi e idipendenti, e non volete accettare ? ? Avrei bel
            dire allora i i Francesi vi ingannano; e
            T vi mancheranno come per il ‘passato 3.
            rifiutiamo l'offerta, prendiamo a forzà.
            _ questi Presidj : si riderebbero di me, e.
            mi direbbero: cosa pérdete a trattare
            l’accomodamento su. tal piede ? Bisognerebbe che io fingessi di creder di buona fede i ‘Francesi, e destramente .
            mantener il popolo fino a fargli scoprire l'àstuzia è malafede del nemico. Se.
            io avessi rifiutato ‘assolutamento l’ar:
            mestizio propostomi ; 3 Pavrei sbagliata:
            presso. il popolo } ma sè osserveretebene la mia risposta, la troverete equi.
            valente ad un rifiuto. Pare a voi chei*
            Francesi volessero abbandonare i posti *
            chge ànno. e farsi bloccare ne’ Presidj ?'Eppure questa mia risposta, inorpellato con termini apparentamente mode-.
            rati, è stata graditissima al ‘popolo :*
            ognun conosce, meglio. d'ogni. altrô il
            suo paese. Se però, in tempo delle prò-.
            posizioni che potessero fare i Francési,
            l'Inghilterrà si fossé dichiaratà, ‘ allora
            sì che sarei inteso, ed: il popolo per
            mano de’Francesi :rifiuterébbe ancora
            il Paradiso ; oh quanto ognuno sarebbe
            invogliato di vendicarsi é del disprezzo
            che di noi dnno mostrato ‘e della SU
            perchieria fattaci! Non mi conviene or2
            prender tono alto ; abbastanza dicono :
            | al popolo che éi-sostieneuna guerra. ché:
            ‘non ha altro oggetto che la mia ambi
            zione privata. Questi sono i discorsi:di.
            Zerbi, di Buttafoco, Marengo e Perés;
            Boccheciampe ed Alessandrini. Mà se
            una vôlta potessi dire: abbiamo una Potenza che ci protegge; e. che vedesse
            ro una qualche squadra in questi mari,il
            _popolo non sentirebbe che a me, che mi
            fa l'onore di credermi zelante della
            sua libertà e del suo’ bene. Ho
            detto al Padre Maestro che faccia da
            giornale ; io non ho tempo. Sappiate
            che dormo vestito da che sono principiate le ostilità per aver comodô di
            alzarmi la notte à. scrivere; altrimenti
            il giorno è poco, In' una burrasca comé
            questa, devo aver l'occhiô sopra tatto
            ed accorrere a tutto.:Noi non siamo j
            Greci, ma il Re di Francia è potente
            quanto il Re di Persia, ed usa la forza
            e l'arte per vincerci. Non trovate siP*
            | le il ritratto dell’Inglese, ma voi dovete
            sapere che io erà allora e sono ancor?
            molto cambiato. Sarebbe un bel colp?
            se d’improviso uscisse il corsaro che
            segnate ; farebbe un tesoro. Fili
            assicurandoyi che, se Dio non mi ca
            bia il cervello, i miei amici non si artO*
            siranno di me, e sostenerò. la causa la
            “mannaia. Se la machina mi ‘ negher?
            coraggio comune a tanti granatief
            mie massime mi conserveranno dU
            che distingue gli onesti uomini de” 19”
            li-parla Qrazio: Justum et tenace</texte>
        <auteur>P. de. Paoli</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="fra">fra</langue>
        <titre>Une visite à Pascal de Paoli</titre>
        <texte>Je parvins enfin à la vue de Je laissai mon domestique avec | Les flots ont de nouveau vomi des mercenaires, cueil; [ ed io vi fard conoscere quanto vi Sono
            Sollacaro ou était Paoli et je| mes guides, et passant les gardes, | frainant comme un boulet.peste,honte et misè- | Etsi la Force est Droil pour ceux qui ont la particolarmente temuto, nè a OStTO
            approchant rempli | je trouvais quelques uns des gens res force, | TE PIOPOSIZ 5
            me sentis en
            de trouble et de timidité. Mes idées
            que. j'avais eues sur son sujet avec
            et de tout ètat qui tous s'étaient.
            accordés à le réprésenter. comme
            un étre au dessus de l'humanité.
            Je desirais avec ardeur pouvoir
            juger par moi-même d'un caractere aussi grand, aussi distingué,
            mais je craignais. què le motif de
            ma Visiteet la présemption que
            j'avais d'aller l'importuner ne.me
            fit paraître bien petit à ses yeux.
            J'eus presqu'envie de m'en retourner sans le voir. Ce combat de
            sentiments .differens .m'agita et
            m'occupa l'esprit pendant que je
            du Général qui me conduisirent
            dans une antichambre, où je vis
            plusieurs cavaliers corses qui l'attendaient.
            M" Boccaciampe lui avait annoncé mon arrivée, et l'on m'introduisit dans sa chambre. Je le trouvai
            seul.
            Son air me frappa. Il est grand