<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE revue[
<!ELEMENT revue (metadonnees,rubrique*)>
<!ELEMENT metadonnees (numero,date,ark) >
<!ELEMENT numero (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ark (#PCDATA)>
<!ELEMENT rubrique (type+,langue+,chronique*,titre+,texte+,auteur+,compositeur*,traducteur*,origine*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST langue lan (cos|fra|ita) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT compositeur (#PCDATA)>
<!ELEMENT traducteur (#PCDATA)>
<!ELEMENT chronique (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
]>

<revue>
    <metadonnees>
        <numero>196</numero>
        <date>1925-03-22</date>
        <ark>bpt6k1330789w</ark>
    </metadonnees>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>In cerca d'un omu</titre>
        <texte>Allonganu ij orni ccrescenu.
        i pinzeri. : Sn
        . Diu ci. guardi | «da cun. bon
        - ghjanaghiu, dicianu l'antichi
        _chi parlavanu par ésperienza è
        "ui si Sbagliavanu niai..
        "Noi, invece,
        - sempre, masimu in pulitica.
        "Avemu avutu l'invernu dol“ce cume "u méle ma Marzu Ù
        tignosi Ci $cùzzula in "capu
        tutte e so barrette piene. di |
        grandina. «Da.:chi -so tanté
        «barrette; ‘cacc’e. metti; cacc'e
        "métti?à dicià sempre ziu Fran"cescu di Murzu" ch'in tempu [;
        chi. 1 forni, sfumicacciavanti |
        e chi. l'ancipu battia senza.ri> posuanli mulini. a si tuccava
        “tutti Vanni a Axburi:i 1n-la fes
        ta dii morti. ~~~ :
        Dopu avè fattù' u binadéttu
        di.tutti i fuculaghj in la-simana. santa si ne turnava À
        Murzu cu..u- so: sumere. carcu |
        di bastelle imbuffate di brocciu muñtagrnotu. —- ee LE
        _Ma quelli tempi so passati |.
        “par sempre :.i mulini Jacenu
        _svintrati sopra. e rive:di i fiumi
        Le nantu'1forni ci nasce a figa
        _isalbatica." Cité I.
        "Furtuna chì nò avaremu préstù l'élèzzione municipale é,in
        mancanza d'altru, ci ‘pudare:
        -mu.ticchià di pulitica;. .
        In la"situazione un c'è nulla |
        di cambiatu-Più: si cerca l'o:
        mu, chi ci vole più Si, càsca in
        le manu.d’unritrabiu.. .. |
        . S’ell’un spunta qualchi fun: |
        "gu durante sti quattr'anni:saTa dinò Landry chi farà l'élezzione. Coty, "cumbattutu da
        l'amici cume da i nimici un
        Pò più. cuntinuà a fà farina cu
        .1 tessi. mulinaghj..
        Gavini:-avia -un: partitu ma
        Tha abbandunatu di nottetempuele pécure sènza T'occhiu
        di u pastore. finiscenu sémpre
        sottu u dente di a volpe. Tutti
        l'altri contanu ancu menu ca
        u bada in- du jocu di» a pri
        miera. Cn
        "Villaria parlà un pocu. di È
        Moro-Giaffeiri ma parla. tantellu ch'un c'è mezu. di ficcà |
        Una parolla! Lascemu finisce
        in tarra a carriera di stu Ministru in  partibus eppò ci n'occus
        Paremu. :"
        Pa u momentu un n' occorre
        di scriveli. ch'un. _ zispond'a a
        imu.
        E.raghione. ch'ellu da di u
        so silenziu sotantu serie ch'un |
        C'È ca a calà a fronte, cu tutti
        quelli chi 1i nè facenu u rimProvaru dice chi 1 so sicritar]
        SI tenenu. e lettare, e cusì si
        tede scusatu !
        ci sbagliému a
        -Amittendu chi sta buggia sia
        | vera,u sciò. Moro, par risparmià
        a-quelli chi liscrivenu, perdita di tempu,-di-carta e di-franchizie duvaria mette: st'avisu |. Céru u cagiu: purcelli ùn si ne strippa:
        in Ju Petit-Bastiais. | | Ùn
        « L'amici, cunisciuti e in |
        cunisciuti,so prigati d'un seri
        ve più .a MorosGiafferri. fina
        i so sicritarj si’ tenenu Tutte
        e lettere. ~~
        avarà u tempu di riceve e di
        risponde». I,
        Certi: lonzi. credenu : chi ES
        Moro €. Caitucoli: si spiccanu
        da u sci Adolf särianu :casica! Un ci pinsate mancu in
        sonniu.
        Landry hà di li guai a ‘passa
        ‘ellu stessu ma dayanŸ’a i.mazzardi chi li si prisintaranucontru farà passà tutta a so lista.
        Arena chi pudia tantu ùn
        narosu e senz 'odiu funu belli
        fittònu.Tutti u: siguitavanu par
        calculu e nimu par affizzione.
        >A la so'morte i più indifferentifunu e nullità ch'avianu
        prufittatu di u so regnu. |
        . Mortu Cristu spentu ulume!
        un ci ne fù unu par virsà.lagrima sincera ne par. lampà
        un. segnu.:-di ricunniscenza
        nantu a.:so spoglia. Landry;
        ch'un face nulla pa: a Corsica
        népii Corsi, pruffita di è circustanze scarse d'omi cume di
        razione. davant'a stu tizzone
        speritu ch’un riscalda ne i cori
        [ne i membri. Or figuremuci
        da éllu a Arena !
        mese di marzu , pienu di ventu
        edi catarri, cù u mese di maghju, carcu dirosule e di fiori.
        L'elettori,, ridotti a sceglie tra
        omu. — | “Ma duva truvallu»?
        ch'ellu sarà Ministru parchi:
        Quarid’ell’ un sarà più. nulla
        paci d'avè un. partitu in Corha fattu. nulla apa u paesè ma
        ~~ "~I Dio xx >
        Ha fattu assai pa i paisani. Gi e
        numarosi quelli chi ne pru-:
        'Ma quelli, par l'Italia, so figlioli ‘’
        È Ligittimi... E,-pa a Francia;:noi?...
        Casinnò a pigli... in piagghia a m 'affiziône I
        'A fngghiaria cum “ella! aissi a tigna. 7
        tuttu u restu. Tutti. so. in amis |
        Saria cumé a cumparà ul
        nepita e puleghiu" cercan'un</texte>
        <auteur>U Monacu</auteur>
    </rubrique>
    <rubrique>
        <type>infos</type>
        <langue lan="cos">cos</langue>
        <titre>P. C. A.</titre>
        <texte>U Partiti ; Corsu d'Azione
        ha dicisu di depone, 1.5 aprile
        chi vene, una palma nantu.a
        tomba di u Babbu di A. Pa
        tria. _ _
        ricuté1 fondi necessarii.
        Avisu a l'amici.
        A sottuscrizione sarà chiusa
        u prima aprile.
        U sicritariu</texte>
        <auteur>Dumenicu Massa</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>Raggiunamentu di u paisani</titre>
        <texte>L'aratu c'è: becchiu, ma vellu : sanu:,
        A coppia.c’è cu tutti i so stàvélli:"
        Mancanui voji: eppò, in due éll'è u rànu ?
        In granaghiu un ne trovu tre granelli.
        E agghiu'a laurà ?... Diteami-voi :
        Sò ch'agghiu'a pone, o jatu San Martina.
        ‘Sumentà di cutecchie ?... -0-poar’a noi!
        ‘Miseria, fame'e morte: eccu.u -distinu:
        Granu unci n'è: so scarse ancu e' castagne:
        ‘Chi magnaremu ? cotalli ? o lasagne
        (Un mi fate scimì!) di tarra pippa ?
        Uvidite stu :chiôsu,: avà cardiccia?- Di
        L'anni scarsi rindia vacinu mena: .Dava pane par tutti; e calchi piccia. |
        Ci n'era pa i puarelli senza: cena:
        "Ma tandu i ino figlioli erariü vivi;,
        ‘(Fatta dui tombi in guerra : o'chi scunfurtu !)
        Un pezzu’ i vigna e calchi palmu d’ortu:
        Sei” racce, a travaglià, d'omi rabusti
        È sperti: u visugnevule au travagliu,
        Chi ci mancava.?-Nulla. E mai disgusti
        Tra noi. Avà, di grazia, pane e agliu !
        Semu- prédaghîi; dite.-o sciò pinzutu ?
        Ba bè: —- famiti e messi in canzunella !
        Spertu era u corsu... quand'ell'è binutu...
        A sparghie q usangue par: ‘salbebbi a pella.
        Ob; tandu sì-baliamu pur: calcosa! *
        Fattu u vizzien all'oca, semu. stracci,
        Bella ricunuscenzà! È bargugnosa;
        Sapete, sta maniera "di trôttacci;
        Si a Corsica f'ha datu,-e bulinteri,
        U fiore di. n.s0 sangue-e:e so più: fresche
        Energie: —-si, par-.te, currinu fieri _:,.
        1 corsi ad appittà é forze tüdesche.
        '* —Si, rainata par te, — si disangusta,
        A Corsica è ridotta all’angunia :- -.:"-".
        Parchè, o Francia, -ti mostri. cusì ingrata ?.
        Parchè un ti fa pietà sta- sorte ria? il.
        . . U sangne côrsu “Ga bale nédngue "almeno | 1
        sos
        Ch; giremu vra
        E stisula, giardinu diu Tirréhu; c:Quantu u Madagascar, d'ariu murtate ?
        Par si-nostri vicini sardignoli, :...
        L'italia spende, dicenu, miliardi.
        Bastordì i?
        Certu di sangue celticu. in dee vene .
        -Un ne emu mancu crea; semu. altra schiatta,
        Beggu, però chi a Francia assai ci tene
        A chiamaeci francesi, — Eppo’ci tratta
        -.Come biduini !— Eccu::di:e duje.una: 0 a Corsica è francese; e un'è pnestà . ..
        Ch'élla, - au descu dia Francia, "stia. dighiuna.
        'O unn'è francese; e, tardu... libertà !
        | ‘— Ragionu male?::: E, prôpriu,nnn' ’agghiù
        A Anzi !) ch'elli ini chiaminu francese. © n i
        É un pèzzu ch'ell'è mortu Carlumagnu:
        «Francese; dunque: sì,ma a- cùndizione .;
        Chi a Francia un mi si mostri mai matrigna; : i
        . Ghiominevardi! .. : Ma;' se fussi: un altru;
        M'affaccaria:a Pariggi. E au prisidente
        Di i Ministri, chi pare bellu sgualtru, . .
        Li diciaria: « Mansiù, statemi à sénté
        Nôi duji emu judìziu: è beru? ..
        C'intidaremu: — Cume, bé vidite .E'so corsu, Mansiù: e. bi dumandu . pomi]
        D'un scurdabbi « dia Corsica. — Infinite. Li
        _So'e so miserie. "ôr ella. u so. duvè ?
        L'ha fattu versu à Francia. Avà chi a Francià
        Fiu versu d'ella u soiu: e farà bè. tà
        A boi, Mansiù, po'bi daremu'a mancia:l» :
        mo. = d~ me 41 _ _
        _.[ Sifa-sente più. bivù ancu l'amore...
        Avianu cu stu chiosu quattr'alivi, dine. i : À
        {anch ellu.
        e tando, MI
        È nun bi pare ‘chi sta pridichetta |
        | Agghiustaria l'affari ?;..Ci si provi.
        A falla, ma cu tutta l'etichetta,
        Ùnu dii 1 nostri diputati. novi ! ls
        _ Tolti, o Francia, i mutivi di lagnanza: |
        ' Saremu diinò amici; e cùn ärdore r
        È legge di natura; Piena'à- panza;
        à .
        ~~ +
        dai ‘ic </texte>
        <auteur>U Babbuziu</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>UNA GRAN NUTIZIA</titre>
        <texte>allegratevi 'Frattelli, VI v'annuni
        tu a Algeri per Tumbuctu. In tuttu giù una gran nutizia.
        U nostru paese à Francia. beni
        saa tutti î. furtunati chi -Divenu
        sottu a. so alta prutezione: Un
        si. scorda di nessunu, mancu d'i
        Negri. :
        _Saperete. dunqué che, di ' pocu,
        è stata inaugurata. tina stradà
        ferrata chi. riunisce Uu Ji îume d'u
        | Senegal a quellu d'u _Niger. Avà
        in trenta sei òre si pò andà da
        Thies sopra u Senegal, a Kuliboro,
        sopra u Niger. 0
        1296 chilometri !
        gri!
        E ‘sapete quandu . 'è custatu. stu
        Papi laboru È |
        | Pirtunati Né:
        CE
        i riccu e generosu. quant'è. riccu. Le,
        (I ehilométru è; èt toinziu 'à 157:000.
        hannu custatu 203.472.000 fr !( dui
        centu. A MÀ miglioni. quattru. centu
        settanta dui. mila franchi Vi:
        Ma.iîi Negri puierannu . ‘andò
        prestu e bè ;serannu. cuntenti e.griderannu.« Evviva ! Evviva a Fran
        cia, cusi brava, cusi generosa : J >
        Forse. mi dicerete : «E a nosirà
        | strada ferrata” d'a Costa Orien:tale duve nè è ? Un c'è che centi
        kilomitri circa da fà. Simmu luntani. dà i I 296. kilometri da T. hies
        a Kuliboro!» _ CU
        Ma Hoi, fratelli. ,cari, un "sii
        Ma a Francia è sempre a Francia :un gran paese mu ‘mica Négri ri. No oi simmu Francesi. Femmu; perte d'a nazione Fran:
        cese. . Simmu quelli chi; danu e
        i mica quelli chi ricevenu. I patroni. di casa, devenu. sempre esse
        serviti .. l'ultimi. Un pocu di par
        qienza... U nostru. giru 'arriverà
        Ma prima bisognerà
        che. Dakar a u Senegal sia riyni
        fe cose “bisogna, a sente. a ragione.
        Evviva, sempre U nostru paese
        a Francia cusì. caru ! ;</texte>
        <auteur>U sciò Pasquale</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>U Tuvagliòlu</titre>
        <texte>Bramu. di. lugliu. “Spricchj ava
        | appena l'alba. U sole un. avia-ancu apartu u s'occhjone rossu. Un
        si sentia, pe'a campagna foltra
        e ;verde,- che.u cantu tristu e longu d'i grilli, cupartu di quandu in quandu da u fischiu armuniosu di u Tussigndlu è sott'a leccaa...
        Si - vidia © “un. ‘Beto FOSSU ; in
        d'inentru c'era u lume. Sa jente
        era sbonorata. |
        Un sumere runcava. in piazza
        N'u mentre che un vecchju Si dava a schjaffalli aso camisgia di
        legnu. |
        — Metti. a manghjusca n'e bisacce, eppò falale ch'è òra, gridò
        u vecchju a u 4itellucciu, ch'avia
        sempre e palpetule. appiccicate.
        Alegru di fassi una. scampagnafa, u zitellettu. Salò e:. qualchi
        mumentu dòpu eranu tremindui
        incavalciati nantu, a lisca di u
        spinu di Bazzicone chi, spidarazzendu, curria.cume.un. fullettu.
        E biaghja e biaghja... L'eria principiava a 'ntebidissi
        e diggià i raggi d'y .. Sole. ;:6ranu...
        [etme: Jante punte di. focu. A stra
        fani. Dumiiia. 1206 chilomitri |.
        da _S'allun mgava, pulverosa È bia
        — Hu ! cum'ell'è calla ato jacchetta, o caccà.!..dicia u relie
        ciu. |
        E d'infatti !. S lu. $ "avia messu
        qualchi coppiu d'òve in borsa.sa-rebbe statu sicuru. di truvallesi
        cotte pe" l'òra i merenda. E buciartule chi si. tendianu nant'u
        e petra a u sole, ingrucchjulavanu supitu a.coda e - firmavanu
        arrustite di colpu. Vi pregu. di crede chi candileri a.î.tetti un sine
        vidia, un c'era. penseru ! I E, furmicule sudavanu cume:;ciarrette
        d'acqua fresca, su. mare firmava
        cume unasuppera;a luna s'era
        guasi tutta sculata e un. si ne
        Vidia più che un. pezzu inturchjatu cume un canistrellu. U sumere cappiava. untu chi parià. UN
        lambiccu, e principiava a calà l'orriechjoni. pee a
        Era circa mezziornu quand'elli
        junzenu au pede. d'un fiume che
        li tuccava a saltà: a guazzu. :È
        zò e zÒ ! nullà'a.fà,u sumere avia
        impuntatu e zampe di davanti e...
        forti lì. E.serebbe fimartu sottu
        a e battulellaie . piuttostu che di
        pone un'unghja a. Pumidu:
        U vecchju si -disse. allòra chi
        forse a sgallozzu u sumeru passerebbe, -e li cacciò a.-so camisgia di legnu, bisacce e tuttu. M a,
        [ahuhu! Bazzicone un volse- mòve
        mancu d'un pelu.
        Bidendu cusì, u caccàtu disse :
        chi bale! u sumeré un lu pudemu lascià quì. Aprisu tuvagliòlu,
        ò Juvacchì ( u zittelliui sì chjamava Ghjuvacchinu ) eppò dòpu, si
        Bazzicone vòle tene a soja,ci n'andaremu.
        — Mi sò scurdatii di pigliallu,
        u tuvagliòlu, o caccà, fece Juvacchinu. U vecchju, a se paròle, un
        vide più lume e si misse, no senza raggi one; a letigà u zittelu ea
        — Eppò a dici avà, sangue d'un
        otrelallòra unci tocca ch'a piglià a
        strada... ajò, ajò ! e prestu ch'un
        semu ancu junti.
        - U zittellu, ca d'u spinu di Bazzicone, chi, |
        spitaraijéndu, curria..cumé un
        fullettu... ~ So U
        E biaghja e biaghja...
        U sole,giallu cumeun lampione,
        pigliava diggià a falata a tronca.collu.
        sparghiesi quand'i nostri. dui su-,
        meri e mezzu un eranu più ch'a
        tiru di fucile da u paese e famiti cume. lupi; E gni tantu u
        -zittellucciu- lampava-:c'un: tagnui
        — Aghju a fame, o caccà. :
        — Un bôle di !' manghjerai in
        casa € cusì imparerai d'un dimenticà u “pane. : fr: | ,
        — Ù panz: FE n ebisacce, ‘6 caccà, inguduppatu n'u mandile ; un
        è cheu tuvagliòlu ch'è fermatu
        ‘nant à carréja. :
        . —Eppò à dici avà? Sangue d'u
        otre vida !...</texte>
        <auteur>P. Borghetti</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>A l'erburu cadutu...</titre>
        <texte>Un canone, di nofte rofighiiava; la
        — À l'appiettu, è cosa intesa — .
        - Ma chi l'òvé e ghialline Si sterbava
        A sapè d'i altri cani era palesa. |
        Ma imbèce d'accusà
        Di u ladru e mille colpe,
        Ci. ircav ogri'un di fassi volpe ivu |
        E di scusà! ~ > SI
        Diva d quelli canone Ini l'arubbécciuù' aiutu Su
        Pérchi si stava miitu ~~. ~~
        | U testinmone:L. inuéénte pretesu ©
        Chi SÌ i francò fin er * a
        Si Séordò dilenteri:":"
        a 2 D'i lacciu tesi:
        | E ruzzava. È sera CT
        «Spiréridir in ni a Furtuna. |
        E mancu a chiar ‘due luna.
        À Furtuna SÌ i sbezza
        E cerca à altra carezza: © È
        ' Inaltru amante: :.
        Si lescia lu ladrone
        Chiappu per una zampa
        _~"Ed'incôllii silampà : ~~ ~
        “el Alu padrone. «=.
        Pensa hi cane zoppu  :fn la pediga chiusa.:...;
        Mà gial''serà la scusà ?... SÈ
        | Un si sà tròppu f°.
        "Si sperghie la nufizia CL
        - A‘cennu di furestu;
        Ed ogni cane onesti ~. Chere... Justizia.
        Cani becchj e zitelli" Canì
        E di pàstor' le cagne, : Ce Uo
        Tutti senza macagne
        Sò questi è quelli;
        È ghiranu in quel mòdu
        Qual sà guantu jalline
        Fecènu a mala fine ~~. -._—In speddu... e bròdu? |
        " S'avanza un cagnulellu
        E ghiura sopra Cristu.
        Chi di notte l’ha bistu Polzà più d’un agnellu.
        «E pò guand’a u pollame *- n
        Di corre un avia l'asgiu,
        Si saziava di casgiu.
        E voglia e fame.
        CES
        E pò lesciemu corre
        — Chi per dilla un ciè lapre —
        Quant'ellu strippò capre......
        A sà u signore! |
        SI u banditu, a l'érmone
        Un ha più lu fucile
        Tand'è > chi l'òmu bile.
        Li sorte in testimone. i
        Ti uttu sòiu fu lu tortu,
        E lu can? festimone
        Ebbe tutf a ragione
        E fece di manera
        Ch'un bastò Ia galera:
        _ Ùn cane è mortu!
        In quant'a la morale di u racontu
        Ùn pretendu pigialla per miò confu;
        D'altri I'hanu pensata e l'hanu detta:
        «Al'erburu cadutu...accetta,; accetta!»</texte>
        <auteur>A. F. Tristani</auteur>
    </rubrique>
    <rubrique>
        <type>conte</type>
        <langue lan="cos">cos</langue>
        <chronique>Raconti da î zitelli</chronique>
        <titre>Cececcu magna a pulenda</titre>
        <texte>- C'é éra, una volta, una mamma chi
        [avìa'un- figliòlu, Francescu, a l'accorta;. Cececcu.
        Cececcu tinia caru a so mamma
        ra di u so figliòlu, sempre ubidiente « e prontu, dicia: .
        ..— Un ci n'è cume Cèceccu Anciù per esse stancu mortu s’iò dicu:
        zo Ceccè, vai e fà cusì, » Cececcu
        parte. e face e volta subitu! |
        Una mane di ferraghiu, un gran
        givone cupria a campagna e un si
        ca chi stava in carcera e muria da a
        fame chiamava, aspessu :.
        — Mè ! ! mè è! Datemi da magnà ! !
        Mè ! cs La AL
        — Senti, a capra cum "elà dumanda ? disse a mamma. Vai fòra; u miò
        n. figliòlu, . tagliati una bella bracciatà
        d'ellera e dalladi ! Intantu, mettu u
        pagliòlu a u fôcu e preparu apulenda.. .. |
        . — 0 mà, fate chiò 1 magni prima,
        rispose u zitellu.-Ci anderaghiu subitu subitu dopu! TO
        ‘= Innò, ' vaici avale chi torni
        prestu! Vai, chi tù sie > prima qui
        che culà! © ©
        ‘Céceccu : un ci vulia andà. Aliòrà
        ° | a mamma li prumesse d° imbutrallu,
        a u ritôrnu :_ pulénda e brocciu sE
        cusì u ti fece parte.
        Fattu a pulenda, aspetta e spetta,
        a manima si inesse a magnà : una
        ‘fetta, ‘cinque e sei, senza cuntallè
        . perchi avìa anch'ella l'appittitu. A
        la fie, s'avipe, cun battimu di cÔre,;
        ch'ell'un fermava più ca "una fetta
        'sòla annantu u tàulù :
        — Hi! Disgraziata, cum aghi fatiugnerà ?.. Rasciò u ‘pulindaghiu,
        ‘nittò bè, cu a cucchiara, u fondu di
        ma. ......,: [a pàaghiòla, ma un ci Ticavò. ca dui
        Si curava: a
        ‘ pallottuli tainante un vi. :T;ti mespiù che l'occhi di u capu e a stav'a [
        sempre a sente. E a so mamma, fiewidia un filu d'arba indocu. A giocna "videndu chi w figliòiu a s'allungava,
        tur Chi dicerà Cececcu quand'ellu
        — O fune leia u bòie, chi u bòie
        un vòle beie l'agua, l'aqua un vòle
        spegne ù fòcu, ù fòcu un vòle brugià a mazza, a mazza un vòle minà a
        Cececcu e Cecéccu un vôle magnà |
        a pulenda.
        A fune un si | sgumintò di u so
        lòcu.
        A mamma si i vultede versu u gra‘naghiù e disse : Fa — O topu, roditi a fune, chi a fune un vùle lià.u. bòie, u bòie un vòle
        beie l'aqua, l'aqua un wòle spegne u
        fòcn, u fòcu un vòle brugià a mazza,
        a mazza un- 'vòle minà-a Cececcu e
        | Cececcu un vòle magnà a pulenda.
        U topu affaccò u capu a un tufode ma un surtì. °
        A la finea mamma ssi vultò. versu
        u migiu'e disse: | n
        — 0 migiu, fnagnati u topu, ‘chi
        u topu. un vòle rode a fune, a fune
        run vòle:lià u bòie, u bòie un vòle
        beie l'aqua, ‘l'aqua un vole -spegne.
        u fòcu, u fòcu un vòle brugià a mazZa, a mazza un vôle minä a Cececcu
        e Cececcu un. vòle magnà a pulenda.
        Subitu ù: migiu si lampa au topu!
        u topu allora. si rode'à fune, a fune
        allòra si leia bòie, u bòie allòra si
        Ì beie l'aqua, Paqua-aliòra si. spegne:
        u fòcu, u fòcu ‘allôra si brugia a
        mazza, a mazza ména à Céceccu e.
        Cececcu si magnò. à pulenda.</texte>
        <auteur>Martinu Appinzapalu</auteur>
    </rubrique>
    <rubrique>
        <type>reprise de publication</type>
        <langue lan="ita">ita</langue>
        <titre>PRIMA E DOPO PONTENOVO</titre>
        <texte>Abbiamo ‘veduto. in un: precedente
        articolo ‘la ‘situazione della Corsica |
        alla vigilia ‘del fatale Trattato di.
        Versailles, che ne > faceva non già
        ÙN ~ parificata
        alle altre, i ma bensi « «un pays d état».
        Doe SUCC GK cervagito pos Curci valtt- CG
        | aspittò. statu una stonda, affacà u
        zitellu, è > spalle è € a barretta c carca di
        ttu." 6? avvicinà da u fòcu imbüratu é
        dicè ; aa mamma : n
        | — Aiò, duv'è sa pulenda? Mi —
        nè magnèria ancu ùna bomba !” .
        A mamma li porse ciò chi ci s’eTra: una fittuccia è dui pastacciuli.
        i - Un c'è che què ? interrugò Cececcu. - AÎlòra à facciu a 'mbiitratà !
        ' Ricusò di tastalla e sbucciò a i piegne.
        e — Magna, u miò figliòlu, suppli:
        ‘cava di povera. mamma. È pôga ma
        è bòna. Un'altrà volta, un mi sbati ne _vogliu fà da
        cu un rispundia ca'tirendu singhioz[ Zi di a so gola chi facia colla 'e. fala:
        ‘ Allòra, a mamma perdì pazienza
        ‘e ‘gridò in collera, vultendusi versu
        |a, mazzà chi stava daretu a L'usciu : :
        — - Mazza; mena a Cececcu chi un
        vôle magnà a pulenda ! I" |
        "À mazza: un' si ruminò. uu
        A mamma si vultede versi u fò:
        cu e disse :
        da. |
        U fôcu un si sgumintò manc'appena.
        A mamma si vultede versu a tinella piena d'aqua i e disse :.
        vòle minà a Cececcu e Cececcu un
        vòlé magnà a pulenda. la.
        A mamma- si vultede versu u
        — Bòie, bèiti.l'aqua di a tinella,
        fòcu un vòle brugià à mazza, a mazza un vòle minà a Cececcu e Cececcu un vòle magnà a pulenda.
        U bòie un trinnò un "orécchia.
        A mamma si vultede Versu a fune
        e disse : _
        | = O fôcu, brugia sa mazza, perchi a mazza un vòle minà a Cececcu
        e Cececcu un vòle magnà a pulen- [
        | Aqua, spegni u fòcu, chi u fòcu
        . | un vôle brugià a mazza, a mazza un
        bòie chi magnava in piazza e disse:
        chi l'aqua un vòle spegne u fòcu, uEpistolario * di Pietro Alessandro Vérlroveremo in abbôndanza notizie curiosè e rare sull’estremo. è
        sfortunato. ‘tentativo fatto da Paoli
        ‘per-consérvare alla - ‘Corsica. la pro:
        pria indipendenza.
        "Dopo .ùn breve; periodo. ‘di silen
        zio la. corrispondenza tra i due fratelli torna. ad occuparsi: delle vicendel 1768, in unà noticina : di 'Alesc
        sandro, si leggè che molti soldati
        ‘francesi disertano e che Paoli li fa
        imbarcaré per dove vogliono.” Il
        Mi di detto mese, : Pietro, scrive ri:
        suluargli che . néll’isola” ‘stavano :per
        arrivare 20° ‘mila vomini* di truppa
        per sottometteria, definitivamente, "e
        che nei:còrsi-nonsi riscontrava nes:
        suna valida disposizione per -:resistere. A Livorno tutti (i. côrsi) parteggiano per i francesi, . ed egli domandandosi;. Cù ‘proposito di Paoli,
        se i còrsi; hanno 'il loro 'Sersé od
        il loro Pirrò, concludè: ci fatti diranmana» .
        Ai primi di settembre;, Pietro, dice che 1 còrsi piegano davanti ai
        francesi comandati da. Chauvelin,
        e che-molti di essi Si arruolano sot:
        to le bandiere reali. E non molti
        ri souo padroni:del Capo Corso, ed
        infine che il colonnello Buttafuocoal servizio. francese, si recò-da Paoli,
        a nome di. Luigi. XV,.è lo. assicuro che i còrsi, : ôVÉ si fossero sottomessi, avrebbero . avuto il tratta{mento di sudditi nati ed altri priL’aqua si stede bassa ind’a tinelvilegi.
        Alessandrô, nôn è contento decome si svolgono le cose nell’isola
        e critica (10 settembre 1768) Paoli, di
        avere lasciato il paese sprovvisto
        di difesa; ‘@ -lo iralta senz’altro da
        «ignorante o tristo >» ! Non solo, ma
        in un, altra lettera lo qualifica
        addirittura di «millaniatore e di Romolo buffone» affermando che la
        stima di cui gode è usurpata, e che
        ha canzenato tulli. - Anche Pietro
        Teva. narra che a Firenze, uscì una
        - sis sn
        de- del} Isola: mel mese di ‘agosto
        no. se haninô là; virtù. greca o PO~. :
        giorni dopo annuncia -che gl’invasoL'agente dei còrsi in Roma
        di dolore !
        pure scrivendu che la condotta del
        Re di Francia è un insulto ai diritti dell'umanità (17 settembre) accusa Paoli di non avere pensato a
        -procurarsi apppoggi di poterize estere, Quattro giorni dopo rincara la
        | dosa, chiamandola « Arlecchino Romolo >, e degno tutt'al più ad essere i! buon segretario d'un legislatore.
        .La : vittoria rapportata dai Còrsi
        a Borgo, vi è semplicemente accennata in una lettera di Alessandro
        il quale parla pure della sconfitta di Olmeta appresa dalle gazzeita di Livorno e di . Venezia, ma
        che l'ambasciatore francese a Roma smentisce. nu
        ‘In una lettera del 12° ottobre,
        Pietro, accenna alla paura’ del Re
        di Sardegna, per gli avvenimenti dell’isola, ‘ed ha certezza - che
        Paoli ricevette soccorsi in denaro
        dagli inglesi di Firenze, due mila
        gigliati. 2
        Otto’ giorni appresso; “Alessandro :
        riesce ‘a sapéré; che dietro réclamo
        | del Re di Francia la « gazzetta di.
        Livorno » (forse. ‘perchè. favorevole agli isolani) è stata soppressa, € ed
        aggiungie . poco dopo.: « Roma è
        corsa quanto possibile » » _sebbéhè
        'all'Ambasciata di Francia -dicésserò
        ‘che ‘essa (la: Corsica) © ‘$i era’ un
        po 'offérta a tutti. Paoli è « un:tiran‘no »,edi soldati -francesi non. mos
        trono che odio. per i còrsi.  :.
        Il 9 novembre, ‘Alessandro, scrive. che Mr Law, ninistro inglesé
        [a Firenze, proibi ai suoi compatriolti d'inviarè soccorsi agli isolani.
        Aggiunge che il Re di Francia; ha
        falto dire al Gran Duca di Toscana,
        di non ricevere più nei ‘suoi porti,
        legni còrsi, ma che il Gran. Duca |
        Vi SÌ è rifiutato.
        - In una immediata lettera succés:
        Stampa che mostra. come i côrsi
        combattino; ventré à terra; côl cane
        accanto~ e che appostati dietro ma:
        ‘cigni. sparano. sul’ nemico. ll I4|
        dicembre dà coniezza al fratello che |
        gli inglesi residenti in Roma sosten:
        | gono "che la loro Corte, manda di
        "nascosto atuti. 'agli~insôrtije chécun ? PD
        inglese ha disegnato  ùn cane che
        p...., Su?’ tre galli. con: da scritta ;
        Libertas !» :
        “Verso la seconda -mietà di gerinaio ['
        1769, .corre voce che a Versailles |
        si è deciso di non più adoperarè
        armi per conquistare. l'isola, ma
        denaro, e che molti CÒrsi si arruolano. solto" led insegne francesi. |
        . Da una lettera di Alessandro del:
        l'8"aprile* si riléva, che il marche:
        [se Fagnani di Milano 'e' Lord Pen:
        brocke "si sono imbaréati. pèr:. la
        Corsica. Penbrocke vide Paoli: e:nè
        rimase entusiasmato : in quanto. . al
        popolo còrso, esso « è il più gran:
        dé della terra >, sobrio, onesto e
        fedele. Lo stesso Lord fece eseguirè da 'ùn pittore. che aveva condo:
        ‘0 con sè un rittratio del generale;
        del quale diceva che rissomigliava
        al Principe di Brunswich. Trovava
        però che Paoli, non era, un abile