<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE revue[
<!ELEMENT revue (metadonnees,rubrique*)>
<!ELEMENT metadonnees (numero,date,ark) >
<!ELEMENT numero (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ark (#PCDATA)>
<!ELEMENT rubrique (type+,langue+,chronique*,titre+,texte+,auteur+,compositeur*,traducteur*,origine*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST langue lan (cos|fra|ita) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT compositeur (#PCDATA)>
<!ELEMENT traducteur (#PCDATA)>
<!ELEMENT chronique (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
]>

<revue>
    <metadonnees>
        <numero>187</numero>
        <date>1925-01-25</date>
        <ark>bpt6k1330781k</ark>
    </metadonnees>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>Riflessioni d’un veru corsu</titre>
        <texte>« A Corsica un é mica stata lampata a mezzu mare per esse
        sottu tutella.
        "Un aghiu mai vistu a P.
        Borghetti. e'unu cunoscu che.
        pe i so scritti in prosa ein
        rima, mà dévu ringraziallu
        d'avemi fattu l'onore di scrivemi a lettera chi A Muvra
        ha stampatu. Di sta lettera un.
        vogliu ritene. che e. parulle
        citate in capu di st'articulu,
        perchè meritanu d'esse zuccatenantu a u marmaru. biancu di l’edifiziu chi serà inalzatu u jornu di wtrionfu di
        l'idée cursiste "e di a vera ine
        dipendenza. di Cirnu..
        U Créatôre. ha- lampétu. a
        Corsica a mézzu mare e l’ha
        dotata di tutti i-climi edi. tutti
        i produtti, a. razza Corsa è una
        “razza speciale. Dunque pudemu
        ripete, senza. ingänu, ste. patulle. di Saveriu Paoli : A
        Corsica. un è mica un dépar        è una -nazione vintà chi ha da rinasce»
        E quest’altre di P. Borghetti:
        A Corsica un è mica stata
        lampatà à mezzu mare per
        esse sottu tutella»e «Per fà
        bè 1' nostri affari, femuli da
        .. per: noi >:
        Ste parulle pònu serve di
        conclusione a'i,miò : articuli
        precedenti: Mi pare .di avè)
        pruvatu chi a- Francia e a pu-|
        "tica un hànu sappiutu o.vu- |
        lutu fà u bè chi no speravamu ; so
        femuluci da per. noi: : -Un cuntemu più che sopr'à noi. Aju        ~temuci- e Dio ci ajuterà !
        Finu a quì avemu. sempre
        i chiamatu a Francià à u nôstru
        succorsu, .e a Francia: ci ha
        rispostu pe a bocca di u so
        presidente. Millerand : « Avete
        vagliu. di. a terra un ‘è mai
        statu incuraggilii, né. ajutatu,
        e accade spessu che u poveru |.
        òmu, dòpu' éssesi tombu tutta: ‘una: stattina. apressu a una
        racolta,a ‘vede distrutta in poghi mumenti da urié grandinata o da una piena.
        d'ellu. è curaggiosu riprinCipiarà, si no ghieta zappà €
        falce ..
        tinente.
        : l'aqua.e.u sole, chi.vi manca?» |
        Un ci manca più che u cu-|
        Taggiu' di travaglià ma u tra-|
        ‘es ‘imbarca - peu cün        È un li pudete. fà un im
        Pròvaru.. di andà a circassi pa
        NE in altrò.
        Quante volte aghiu intesu
        . Per fà bè i nostri eiferi, femuli da per noì. »
        _P. Borghetti.
        un babbu di famiglia tene
        ste parulle : « S'eo. possu,
        vogliu apre l'occhj ai miò figliòli perch'elli
        arumà aterra»..
        Istu babbu. di famiglia, senZa vulellu, cuntribuia cusi a
        spupulà a Corsica e a lascià
        [ingrandà a macchia intornu a
        u so campu. Di stu male a
        culpevule ghiè a nazione
        chi un face: nunda per ajutà
        u travagliatore: a _ vive di u. so
        sudore.
        - Chi ci resta a fà : Di al
        Aÿemy a scéglie fra duè strà        de :0 corre tutti.apressu a l'impieghi, o insisté a travaglià ne
        i nostri loghi malgradu e gattive racolte, e malgradu i i stenti- suvente inutili...
        Chi strada sceglite ?
        A mea a vi feraghiu cunosce prestu. In tantu ritenite ste
        ca stata: lampata a mezzu mare per esse sottu tutella...
        fà bè i nostri affari, femuli
        da per noi. |</texte>
        <auteur>Sambucucciu di Casinca</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>PARLANU I MORTI!</titre>
        <texte>(Paoli e Napuleone)
        Paoli. — Quandu lasciai la terra,
        eri già, tu, maestru di l'Auropa...
        Facivi trimà i vecchi re, e avà. chi
        ti vegu ne i Campi Elisi, in mezzu
        a tanti prodi suldati, dimi quale fu
        ù to distinu...
        ' Napuleone. — Destinu tremendu u meo fu !... Cunobbi tuttu di e
        vicende umani : grandezza. militare,
        speranze e délusioni..
        Paoli. — Una cosa sòla ti mancò : a stima d'i veri Còrsi.
        Napuleone. — Infelice ricordu !
        Ma parlemu di te... Sì mortu.in esiiu fra i nostri nemici, onuratu. da
        tuttu un pòpulu...
        . Paoli. — L' Inghilterra mai un fu |
        ‘a nostra nemica. e, sòla a Francia
        fece a noi una guerra accanita...
        SÒ
        mortu.in Inghilterra inda nebbia
        di Londra, luntanu di a: miò. cara
        isula, e tu ?.. E
        Napuleone... — Fui. au miò  tornu in Inghilterra, ma cume prigiu-’
        neru di guerra..
        Paoli. — A: Francia t "ha dunque
        pagatu d'ingratitudine : ?
        Napuleone, — Si:e no 1!..:
        Paoli. — Parla chiaru...
        Napuleone..— I Francesi .m'ha- ['
        nu- traditu e abbandunatu. ne l'ultiparulle: À Corsica un è u j_, Pà guerra è fui Obligatu di scappà..
        Pàoli. — Vergogna !...
        Napuleone. — Ma tutti i mari
        eranu chiosi, e finalmente dumandai l'ospitalità, a. u populu inglese...
        Paoli. — E, cume me, finisti ito.
        jorni, a Londra P .
        _ Napuleone. — NO! Fui. ..mandafu
        in un'isula luntana, a 8oo chilometri d'e coste. d'Africa, a SantaElena !.
        Paoli. — Mai Francesi hanu forse tentatu di rendeti l'onore e a libertà ?
        _— Nàpuleone. — Nulla fecenu !...
        Paoli. — Sciaguratu ! Eccu quale].
        fu a to ricumpensa... Ma cosa n'hai
        fattu di a nostra povera mamma ?...
        L'hai dimenticata e per sempre incatenata à u carru d'u vincitore !.....
        Ab ! Se t'un fussi mai natu, a Fran-.
        cia sarebbe una nazione senza prestigiu militare e a Corsica averebbe
        cumpiti i so veri destini...
        Napuleone. — Nasciva quandu a.
        libertà muriva... Trenta mila francesi devastavanu a Corsica e questu fù u primu spettaculu d'i miò pri-.
        mi jorni...
        Paoli. = E malgradu ciò hai ser-.
        vitu i cunquistatori...
        Napuleone. : — Sérvitu aghiu a
        Francia cun onore... Ella mi deve
        à so più bella pagirid di stòria... _
        Paoli. — Megliu averisti fattu di
        (restà in Ajacciu per métte a to spada a u sérviziu d’a Corsica:
        "Napuleone. — Un aghiù fi forse eo
        | vendicato i morti di Pontenòvu ?
        _— Paoii. — Un hai vindicatu nulla perch'è simu sempre carcicati da
        i frustéri... Aviva fundatu un gu-        vernu naziunale e stu guvernu era
        un raggiu di libertà. Aviva fede ne.
        | l’avvénire quandi a ‘Francia — bense in càsa nostra... Ma u jornu; benera ch'a Corsica, — libera -è' rispettata "piglierà ù' corsu naturale
        di a so stòria..
        - Napuleoné. — U jornu. d'a vinU detta ?...        
        Paoli: — Cusì sia.</texte>
        <auteur>Ageniu Grimaldi</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>Cusi ch'ell' un fussi !..</titre>
        <texte>Petru Santu, òmu cassu dai penseri, dai sguerni, da e fatighe ; frustu da a vazza e da. l'aquifraghiu ;
        dòpu avè passatu tante nottatea u
        serenu, lapidu intintu, nant'una remiata di vinestre, s'ingonfiò cume
        un bottacciu... e pigliò lettu. O figliòli! fin'a quì un c'è da ride : porebbi accade ancu a me, ancu a boi;
        Dio ci ne guerdi! Preghemucila
        bona!
        Dunque beccuci qui in faccia d'un
        eristianu malmalatu e poveru in canna ! | | |
        Or sapimu tutti chii dottori un
        sforcanu miccà e schinche per una
        scappellata, quessa si. sà !
        Bellu liatoghiu è u pover'òmu chi
        face a scimità. di cascà malatu.
        Ma un sò quì per "circà ruzziga
        a i dottori,.... ch'iò i vega sempre
        quante avà, sell'è pe u megliu.
        U fattu si stà. chi Petru Santu.
        peghiurava, da-un minutu a Paliru.
        Ci j junse u prete d' 'Aléria, chi quel        {tu pò ci capia: aù ! un c'era l’erte
        di sgonfià!
        Gi capitò u frate di Panchéraccia, cu a so buttiglietta: d'untu chi
        _: succhiu d'erba santa, d'igheru, di finochiu, di
        mintrastu, di patellu, di pélle di
        serpu, e d'un'altr'erba ch'un ne spuncun l'annate
        diritte. Sfilinga e dalli ! Niente a fà !
        Cum'iò v "aghjù dettu, quella di fa
        falà u dottore da Corti un ci vulia
        mancu a "pensalla. Quelle di lesciassi dinò una persona stachittata sot-.
        tu fascime senza dalli nisun riscat        ‘ tu un pò andà,
        A l’ultima, Carl'Andria, mezu parentellu,' 'òmu ricapitatu, si tirò
        quassù, per sénte..
        — Caru meo, li disse u dufiore,
        ‘chi bulite fà È. Senza bede a persona "malata un si pò mu arrisiCìiè "tante
        malatie a i tempi d'ôghié.... chi ciè
        bisognu "di spalancà lochj. Hanne
        [ frebba ? 'A lingua cumu l'hà ? Ba bè
        di comidu ? State a sente : li derete duie cochiarine di què, a dighiunu e pò st'etima chi bene, s'ellu
        s'è- bivu; mi collerete un : bichieru
        d’urina. Cusì "ferete.
        A serà a terdi Carl'Andria rièntro è Pétru Santu s'era appena appillicàtu.
        Un bale a-pena, di discitallu ; senlti. quì, disse. a a moglia. Mi, dumaitina,. à dighiunu, li derai duie coJ:chiarine... di-sl'affare quì, e pò Luni
        ci. vorrà à. collà torna -dùve u dot        ‘tore, per dalli capu e' -portalli un
        bichieru d'arina.
        : = D'urina ??.
        —Ié! d'urina !... Di pisciu, via !
        A. Dumènica. sera, a moglia, da
        . donna prudentissima, hun. lesciò
        mai
        spighe. in .daretu — per timanza d'esse in riterdu o d' un avenne bisognu u Luni da mane —si fece. una spisciulata n'entr'una caffittera... e pò ha t'imbuttigliò..
        A mane dôpu, temp'a l'alha, Carl'Andria, cu i raguagli in mente e
        l'urina in. stacca s'abbiò..,
        Rimesse tuttu a u sgiò dottore.
        — Posate a pena,.li disse quessu, da quì a una stunduccia .bolteuna risposta.
        Dop' avè misciulatu st'urina, u dottore s'affaccò cu u so scurzalone
        biancu, scapigliatu e incirlitu, fieru
        quante avè sgradigatu una rugula:
        a teme ! È incinta di sei o sete mesi !
        — Cumu incinta ? ?...
        — Chi c'entre u cumu ? Sile voi, u
        dottore, o chè 2.... Andate, andate,
        chi li passarà.... Binti franchi !
        E pò usi lesciò.... =
        Quandu Carl'Andria ghiunse in
        casa i truvò éutii in stanza di Petru Santu. Tempu ch'ell'affaccò :
        — Allòra chi l'ha dettu?
        "Ah zittate; zizzate, pò bidè ; un
        mi parlate di 1 dottori, o di cum'ed'elli o amosciassi ! È pò. quessu ©!
        capisce quante Orsu Ghiuvanni a
        leghie a «stateghia. M'ha bulsutu inficuli chi a persona è incinta !
        Petru Santu, incionfatu in quellu sguaglile tirò un. SUSPITU :
        D . . 2 ? I
        — Ah ! disgraziatu !... Cusì ch'e
        l'un fussi ! ! »</texte>
        <auteur>A. F. Tristani</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="fra">fra</langue>
        <titre>CRONACA AIACCINA</titre>
        <texte>, Théàtre Municipal
        _Foule particulièrement dense au
        S' Gabriel où la grandè artiste CoPa Laparcerie, l'émouvante Fabienne de l'Insountise, tient la scène
        trois Jours durant avec sa maitrisé habituelle et un art Cousommé de grande tragédienne.
        Tout Ajaccio veut voir -jouer
        l'Insoumise par la belle Cora; femme de Jacques de Rickhepin, l'é        srivain bien connu et belle-fille de
        l’éminent Jean Richepin, de l'Acalémie-- Française, un ami de notre
        le qu'il. visita à plusieurs reprises.
        Ajoutons que ces: sensationnelles représentations seront suivies à
        ref délai, dé soirées pugilistiques
        lu plus haut intérêt ; rencontres
        que M. ; Ricci, lè sympathique
        lirecteur du théôtre est en train
        l'organiseà avec des boxeurs “de lime.
        Le noble art étant très prisé, ici
        10u5 SOMMES d'avance certäins du
        succès le plus retentissant.
        Kyrnos
        . La Revue corse Kyrnos paraîtra
        ncessamment sous l'éminente. direcion de notre ami Paul Graziani, l'érulit archiviste-paléographe de la Corse. Elle sera rédigée en langues corse,
        ‘rançaise et italienne et y collabore        "ont les meilleurs écrivains: critiques,
        historiens, poètes et prosateurs.
        Les nombreuses demandes d'aboniement et de collaboration que son
        lirecteur-reçoit quotidiennement soni
        in témoignage éloquent de la néces        ;ité de cette Revue et du succès
        lont elle est assurge. ~w
        A ce nouveau confrère A Muvra
        idresse ses plus cordiaux souhaits
        le bienvenue.
        .Le baromètre demeure-obstinément
        tu beau fixe depuis six semaines ef
        l'est bien en ce moment — et seuement en ce moment — que notre ville
        nérite son appellation « d'Ajaccio la
        Blanche ». I
        “La mer ‘est d'huile ;le ciel est d'un:
        leu incommensurablement profond,
        vas: un nuage, si léger soit-il, ne vient
        ni troubler la pureté ; et le (soleil
        lune éclatante luminosité augmente
        ‘haque jour le nombre des lézardsjui se chauffent -voluptueusement à
        ses bienfaisants rayons.... Ofium cum
        Zignitate. |
        Vandalisme
        Les Mimosas $ont en fleurs ét
        10S petits voyous ne l’ignorent pas.
        Aussi sans égard -aücun ét sans
        ‘rainte mettént-ils en: coupe ré        zlée les plus beaux arbres en les
        nutilant férocement. di
        Bien entendu est-il bésoin de le
        lire — on laisse faire.
        Nos :-vandales peuvent opérer à
        ’aise et en auraient-ils la force et
        es loisirs qu'ils pourraient déra        ‘ine tous les mimosas de Pavenue
        st les emporter chez eux sans être
        l'avantage inquiétés.
        Hardis, les gas!</texte>
        <auteur>Inconnu</auteur>
    </rubrique>
    <rubrique>
        <type>traduction</type>
        <langue lan="cos">cos</langue>
        <titre>Maria Jentile</titre>
        <texte>Versu a fine di l'annu 1768. 1
        Francesi avianu occupatu Oletta,
        paisone di u Nebbiu. Cuniscendu
        l'impurtanza stategica di u postu,
        Pasquale Paoli,d'accordu cu i paisani, circava di ripilialla e di fà prigiunera a guernigione d'u paese,
        forte di 1500 òmi e cumandata da
        u marchese d'Arcambal. Ma 1 nimici eranu in suspettu; pruclamonu a
        legge marziale ; i paisani un pudianu più fa nulia. | |
        In Oletta un si sentia un ziîtu,
        Un'òmu, Ghiîuliu Saliceti, chitò un
        ghiornu u paese senza U permessu
        di a guerdia frencese è pigliò campagna. A u ritornu fù messu in prighiò;ma pocu tempu dôpu era cappiatu.
        U giuvanottu rientrò in casa sò1a,
        pienu d'ira per l'affrontu fattu da u
        nimicu. Inquant'a me barbuttava una biestemma contru i Francese odiati. Un sargente u sente eli mena
        in piena faccia. L'affare si passava
        davanti a casa di Juliu, quandu
        prete Saliceti- dettu Pivarinu —
        pevaru di Spagna — per bia di a so
        natura ardente, si truvava a’ finestra. Bidendu minà-in faccia a u so
        parente, Piverinu sentì u so còre
        brusgià... - |
        Tempu chi Ghuiliu,fòra di suminatu si lampa in casa, Peverinu u porta in camara. Dòpu un mumentu surtinu tutti e dui, calmi ma pieni deQE
        A noite, altre jente si riuninu
        -duve Saliceti. Eccu e decisioni chì
        funu pigliate; fà saltà a chiesa, chì
        era a caserma d’i i Frencesi, bendi-.
        càssi per liberà a Corsica.
        Scavonu una mina chi partendu da
        a casa Saliceti, ghiunghierebbe sottu a chiesa, e dòpu avè fattu sa galleria, ci. messenu tutta a polvara
        ch'elli avìanu piatta. A chiesa duvia
        saltà u tredeci ferraghiu a l'annuttà.
        .U core di Juliu. era talmente ingricipitu da l'òdiu ch'ell'era turnaiu
        cume una palla di catana — « dumane dicia, tuttu arrabiatu, dumane,
        lasciatemi accende a mescia ! M’hamu minatu in faccia! D'un colpu vogliu mandalli in'u e nule, lampalli
        fòra d'Oletta cume palle di muschittoni... " la
        — Ma e donne e i zitelli un la sanu?
        E case. e a jente di u vicinatu salteranu anch'elle? __ |
        — Ci vòle ad averteli, ordinalli sottu una scusa qualunque d'andà a'mutescu,. all'òra fissata, da a perte. opposta di u paese.
        Ciò chi fù fatta. ;
        Ouandu,a.sera, l'òra di u subissu [.
        s'abicinò si vide vecchi, donne ‘e
        zitelli, andà infurati a l'altra perte
        di u paese, « cunsultassi cun misieru : i sguerdì incerti tradianu a peu-.
        ra di un periculu scunusciutu.
        I Frencesi si dubitavanu di qualn , ~l cosa. -Una staffetta di ù generale!
        La Température | È
        Grand'.Maison: ghiunse,:a briglia sciolta, a preveneli di ciò chi si
        preparava. Un traditore avia denunziatu u cumplotiu. I Frencesi corsé        nu subitu in casa di Saliceti, truvonu
        ‘a mina e l’impresa inferdale andò
        auveniu. ie
        Saliceti e uni pochi di cunghiurati
        ermati passonu a mezzu a' nimici e
        pobbenu scappà. Altri funu pigliati e
        incatinati. U cunsigliu di guerra ne
        cundannò quatordeci a u suppliziu di
        a rotta. Sette disgraziati funu esecuUn ghiornu si vide sette cadaveri
        ésposti publicàmente nantu a piezza
        di u cumbentu d'Oletta. Si avianu da
        stà senza sepultura : 'u culinellu frencese avià difesu, sottu pena di morte, di caccialli di lôcu e di intarralli.
        -.In Oletta ci era u terrore. U. timore di a morte era in tutti i còri. Un
        si vedia un fiatuper e strade, u fò        cu cra spentu in ni fucôni, e vocche
        "mute, un si sentia che singhiozzi.
        Tutti stavanu, in casa, ma di pinseru eranu in piazza a u Cumbentu
        duv'elli iacianu i sette cadavcri.
        Venne a prima noite. |
        Maria Jentile Montalti era in’a
        so camera. Un pienghia mica: calata
        nantu u lettu, u capu ghimbatu in
        peltu, e mauu nantu € dinocchie,
        l'occhi chiosi ; qualchi volta un singhiozzu li surtia da u core.
        In'u calmu di a nolte, li si paria
        di sente una voce chî a chiamava
        « O Marì!» Durente a notte, 1 MOrti prununcianu suvente u nome d'una persona cara. Quellu chi li risponde mòre.
        — O Bernè! sclamò Maria.
        Ma quallà, vicinu a' cumbentu, Bernerduiacia nantu i farri micidiaghi.
        Di i sette morti, Bernardu era u più
        giovanu, era u'nnamuratu di Maria!
        Fra un mese s'avianu da immarilà
        E avà stà appiccatu a a forca.
        Maria Jentile si ne stava ina so
        camera bughia, ma tindia l'arecchie
        versu ' cumbentu. U so còre luttava
        cu aso ragiò. Li si paria di sente a
        Bernardu chi li dumandava una sepultura da cristianu.
        Piglià un cadaveru da quelle forche e dalli a sepultura .era circà a
        morte. Maria vulia supelli u so'innamuratu e pò mòre.
        Aprì pianu pianu a poria di à so
        camera per sorte. Passò 1n'a camera
        duve ripusavanu i so vecchi, s'abbicinò di u lettu, ascultò u so rispiru :
        durmianu! U so còre cuminciò a
        trimmà; erà figliôla sòla, arrembu
        di vecchiaia pe i so parenti pensava chi s'ella fussi venuta a mòreé per
        a manu diu boja di sicuru ch'elli
        un puderebbenu sopravvive a tantu
        dulore. Si. sinti dunque abbattuta,
        sciambarò e fece un passu indaretu.
        per riturnassine in caméra.
        ‘Ma sinti di nòvu a voce pienghiente di Bernardu gridalli: « O Mari!
        O Mari !. Eo t'adurava e tu m'abandoni ! Stu corpu -struppiatu cuntene
        u còré chi s'è spentu cu l'amore.
        Dammi a sepultura in. chiesa di
        San' Francescu, *in'u a tomba di
        mei ! ». Ùn |
        Maria aprì a pôrta di casa e. surtì
        a mezu bughiu, s'avanzò versu a,
        piazza di u cumbentu.
        A notte era scura. Per mumenti
        a timpesta cacciavai nuli e à luna
        schiariava a farra Ma u lume- celeste, -d'orrore s'imbuglinava
        n'u so velu; perchè quallà,bicinu a'
        u cumbentu, sette morti ghiacianu,
        unu accant'a l'altru, nantu a forca.
        "Daa cimadi u campanile u ciocciu e a malacella lampavanu î so urli spaventosi : era u voceru di i povari e di i nucenti castigati. Bicinu
        | a’ piezza, un granadieru a si spas1 sighiava, u fucile à l'ermone. Pienu
        di spaventu si cupria a laccia cu u
        sô mantellu e, biaghiava pianu pia- |
        nu. Maria s'era ammanlata cu a so
        faldetta per piettassi megliu. Duman-'
        dendu u succorsù-di a Santa Madre.
        di? dulori s'avanza- cun passu decisu
        versu à forca Bernardu era u settimu... u. staccò ; Ù so còre battia ; pigliò u cadavàru in bracciu, u messe
        nantu e so spalle. Era diventatà fôrte.
        U purtò in chiesa a San Francescu.
        Custì fece retta; rispirò, nantu'i $ca-'
        lini di l’altare ; un luminellu brugiava davanti a u quadru di a'Madon-        na di' dulori. U-corpu di Bernardu
        avia toccu e dinôcchie di a giôvanôtta cume quellu di Cristu e dinocchie
        di a Madonna: o o
        In chiesa nisun rumore, nisun lume for’ di a luce fosca di u lumignô        lu chi brugia davanti a'figura di a
        Santissima Vergine ; fora, di tantu in
        tantu, un colpu di ventu,- pòi .u silenziu. n | I
        Maria s'alzò. Ripuni cun precauzione u cadaveru di Bernerdi sopra
        i scalini di l'altare è andò versu a
        tomba di a so famiglia, l'aprì, pòi
        pigliendu u mortu Ii dede un baciu
        e u fece falà pianu in'u a tomba e a
        sarrò.
        Maria restò un mumentu davanti
        a figura dia Madonna e pregò cun
        fervore implurendu a pace céleste
        per l'anima di Bernardu. Pòi si al        | luntand in silenziu è rientrò in casa
        in'a so stanza.         A alba si vide ch'un cadaveru
        mancava e ch'ell'era quellu di Bernardu. Sta nutizia si sperse subitu
        in paese e i sullati gridonu all'arme.
        Si cridia ch'i parenti di Bernardu
        avessinu suppellitu di nottetempuu
        sventuratu figliòlu, e si lamponu subitu in'a so casa. I sfurtunati parenti funu subitu incatinati e chiosi- in'a
        Torfa. Cundannati a morte prutestonu in banu d'a so innuncenza; à~
        ziu.
        Chiosa, in'a so camer a,MariaJentile seppe l'affare. Senza dì una pà        ‘rolla corse da u comie de
        ch'erà in Oletta. Si lampò a-i so
        pedi e cunfissò u so delitu.
        -« Aghiu, dissè, datu a sepultura
        a u miò innamuratu, meritu a morte,eccummii,ma cappiate si nucenti.».-:
        U comte un cridì mica subitu a e
        parolle di a giuvanotta, li paria impussibile ch'una donna debule fussi
        capace di tale eroismu, ne ch'ella. avessi à forza di fà. ciò ch'avia fattu
        Maria. Ma quandu seppe a virità, fù
        prufundamente cumossu « Vai, nobile giuvanotta, disse, vai a liberà
        da per te i parenti di u to innamuratu, e possa, u signore, ricumpensà u
        to eroismu »
        Listessu iornu a forca fù cacciaia
        cù l'altri sei cadaveri ai, quali fù
        data una sepultura cristiana.</texte>
        <auteur>Gregorovius</auteur>
        <traducteur>Mattei-Torre</traducteur>
    </rubrique>
    <rubrique>
        <type>piece</type>
        <langue lan="fra">fra</langue>
        <titre>LA QUESTION SEGONDAIRE DES COURS</titre>
        <texte>Scène pour une future revue.
        La scène se passe au chef-lieu de l'ile de
        Honoloulou, 38 Cours Petitval, au deuxième
        étage, récemment loué à une école de jeunes
        filles. A l'entrée, anticùambre où donnent les
        portes des-salles de classe. Ces portes sont
        ouvertes et de chacune vient un bruit assourdissant de conversations entrecroisées, un
        brouhaha général. Au milieu de l’antichambre
        se tient une surveillante. Elle tire de son sac
        de petits morceaux de coton qu’elle roule en
        boule entre ses doigts et s'introduit dans les
        oreilles. Entre un Monsieur.
        Le Monsieur. — Pardon, Mademoiselle, excusez-moi de vous déranger.
        La Surveillante. — Hein! Vous dites ?
        de. (Haut) C'est bien ici l'école des
        nouveaux cours secondaires ?
        La S. — Maïs enfin, Monsieur, ditesmoi ce que vous désirez. (Elle retire
        vivement le coton de ses oreilles).
        Le M. (à part) — Sourde ou distraite;
        peut-étre les deux.
        La S., qui a entendu. — Ah! dites
        donc, je ne suis ni sourde ni idiofe. Je
        me mets simplement du coton dans les
        oreilles pour ne pas le devenir.
        Le M. —. ll est vrai qu'avec ce vacarme... Mademoiselle, je suis le pére
        d’une élève. J'ai vu dans les journaux
        que les plalonds inquièfent les propriétaires, et je viens voir...
        La S. — AA, oui! Les journaux...
        Vous tremblez pour les plafonds? Je
        vais vous prouver leur solidité. Tenez.
        (Elle se met à danser) Schimmy.
        (Elle
        danse). Le M. — De grâce. Si les poutres
        cédaient...
        La S., change de pas,
        et annonce. — La matelote.
        danse). n
        LeM. — Mais voyons... C'est imprudent. nu oc
        _ LaS., changeant de pas. — La gigue.
        (Ellé danse la gigue). Le M. — Assez, Mademoiselle. Songez à notre vie. i
        La S. — Ah! Vous craignez pour les
        plafonds! Je vais vous faire voir. Le
        chahut! (Elle danse un chahut écervelé, levant. les jambes et mettant les
        pieds sur le nez du Monsieur qui ne dit
        plus rien). n Une voix, à l'étage au-dessous. — Ha
        da finiscia sta cumedia, si o nò?
        Le M. — Quélle ést cette voix ?
        La S. — C'est l'île qui remue. De
        temps en temps elle a des frissons,
        comme ca ; mais personne n'y prend
        croise les bras,
        (Elle
        garde. (Elle annonce) La Java. (Elle |
        danse et chante).
        " Qu'est-ce qui dégot'
        Les écoles
        Du département;..
        L'Institution, ©
        - Les pensions. _
        Et tout l’tremblement ?
        Ce sont nos Cours
        Aux cours toujours courts.
        Où les enseignants,
        Trop surmenés, :
        Sont tous remplacés
        Par des surveillants.
        Récréation!! Nous sortons
        Tout Ie long d' la rue.
        Matin et soir
        © Su’ l’ trottoir .
        On nous passe en r'vue.
        Les beaux’ garçons,
        Sans peur ni façons,
        Défilent devant nous.
        ‘Y en a des blondes,
        Des minces et des rondes,
        _ Et pour tous les goûts.
        _— goûts!
        Le M. (à part) — Elle doit 8tre-sourVaux.
        _
        La S., s'arréte essoufflée, — D,,,
        nous ne sommes que sous-locatai
        Tout cela regarde ce débroui Po
        DNS uillard d
        Le M. — Philippe Daudet?
        La S. — Non, celui qui no
        - e ; , us ,
        tallés ici. Comme qui dirait le co
        manditaire LE l'établissement. E
        ien, qu'en dites-vous ? Les |
        sont-ils solides ? piafona
        Le M. —- 7rès solides, Mademoi
        mn
        Mais ne pensez-vous pas qu'une ùn
        xième démonstration ?.. ci
        La S. — Non. D'autant plus qu'y
        Professeur pourrait venir par hasarg
        Le M. — Mais au fait, où so
        les professeurs ? ni don
        La S. — Où voulez-vaus
        soient ? Mais au collège !
        Le M. — Et quand viennent-ils ici
        La S. — Ici! (Chantant) Peut.ar;
        demain, peut-étre jamais,.. (Pa ré) E
        tout cas, toujours versonze heures.”
        Le M. — Et à quelle heu
        vos élèves ? 7 Ì di sorten
        La S. — A dix heures et demie.
        | Le M. — De sorte gu'ils ne voi
        jamais les élèves pour faire le,
        cours. | I
        La S. — Ils se rencontrent dans le
        rue. D'ailleurs gu’importe ? L'ess ;
        tel, voyez-vous, c'est de pouvoir affir
        mer au ministre que l'école fonctionne
        A ce moment on entend des voi:
        dans une classé voisine : Poussez
        Poussez ! Aïe ! Elle est trop grosse
        Elle ne passera pas. Laisse-toi faire
        Amélie! Ne résistez bas, Mademo:
        selle, laissez-vous aller. — Aïe! M,
        man! Aie! On-me faitmal!... © ‘
        Le M. — Mais c’est la voix de m
        Qui,
        fille! Que sé passe-t-il ?
        La S.-— C'est le chinois de l'établi
        | — € abli.
        sement qui donne à ces. demoiselli
        une petite séance... motselle
        _Le Ma. les mains dans cheveux, le
        yeux hagards. — "estdites ? 15! Qu 5 e que LOU
        La S. — Oui. Notre inspecteur d "a
        cadémie a imaginé un système de la
        | minor. C'est le système B. Ià Oì
        passe les éléves au laminoir pour: le
        faire diminuer de volume. On a di