<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE revue[
<!ELEMENT revue (metadonnees,rubrique*)>
<!ELEMENT metadonnees (numero,date,ark) >
<!ELEMENT numero (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ark (#PCDATA)>
<!ELEMENT rubrique (type+,langue+,chronique*,titre+,texte+,auteur+,compositeur*,traducteur*,origine*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST langue lan (cos|fra|ita) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT compositeur (#PCDATA)>
<!ELEMENT traducteur (#PCDATA)>
<!ELEMENT chronique (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
]>


<revue>
    <metadonnees>
        <numero>195</numero>
        <date>1925-03-15</date>
        <ark>bpt6k1330788g</ark>
    </metadonnees>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <titre>U centenariu di Pasquale de Paoli</titre>
        <texte>alb; cingue;. ‘aprile. chi vene,
        £atanu duie-cent'anni ch'è. na;
        "tu Pasquale è dé*Pagli:'Ghiè*u
        nostra. duvére. di Cursisti, , di
        dà, u 1ornu di.sa. sulennita,
        "un'a filiale pròva: d'a ttaccamen- i:
        ‘veraci, parchi ‘a di parole; lenaci del segreto, lontani dalla 
        “ta è di “grande” ricunuscénza,
        a.u-babbu. spirituale . di a Cot-)
        frivola corrutrice allegria ;
        ‘sica. Bisogna a fà chi su.-iornu
        ùn passi mica scorsu in la me: .
        moria ‘di nostri cumpatriotti.
        .Cume d'altri centenarii, quellu
        di Pàoli. merita.:.di ritene l'attenzione, non sòlu di a Corsica "ma ancu di l'Auropa.
        Un fù ellu w'primu a scuzzulà e catene di, a~ ‘schiavitù ir
        un seculu in lu -quale un si
        cunuscià nè libertà di persona 
        nè di pòpulu, : 'attiréndii. cusì
        sopra ad ellu eau fieru pòpulu I
        ch'ellu "cumandava, * sguèrdi
        ammirativi di e Nazioni Auro- [
        pee. ? -Un fù ellu,-cume disse... "PB.
        (Bretagna; insieme: “provincia 
        francese e nazione, come al
        non
        Tommaseo in du so -aïnimirdbile Proemiü. ae Lettare di!
        Paoli; chi « diede concordià
        a una gente divisa, a una rivoluzione forma .di sapiente governo, àd un ‘isola’ augiista è
        _ povera. spieridido luogo nellà 
        storia délmondo. >? Un fù ellu :
        u precursore di u muviméntu
        genérosu chi scosse tutta l'Auropa; e chi dede a tutte è nazioni e libertà. e ‘1 _privilegi
        ch'ell'un. avianu. mai cunus* ciuti? St'azioni un sò degne di
        u liberatore. di 1’ America;
        Wasington ? Poco
        Stu centenariu merita l’onori ché u nostru còre generosu,
        per una cusì sacra memòria e
        venerata, bòlé rénde a l'eroe, 
        ammiratore fervente di i grand' À.
        òmi di l'antichità, di i quali;
        _ seppeimità cu saviezza, l'eroi» 1
        che lezziò di stoicismu, ch'ellu.
        n'avia ricevute, ‘perchè, sullatu
        vintu da a forza,. ma micca dise
        peratu,seppe, invece di troncà
        a so spada, mettelain u foderu
        È dunque necessità di ringiuvanì a se memòria, perchi
        nissun-figliu di. Cirnu scordi [
        u so nome. Tommaseo finia u
        Proemio di u quale avemu digià parlatu, cun ste paròle
        carche d'amore e di pia ricunuscenza, che noi vulemu cità
        in-fine di st'articulu, perchè
        tuttu Corsu duverébbe sapelle
        a mente , sgurgate ch'elle sò da
        u più prufondu diu còre di su
        ‘grand’amicu di a Corsica :
        « No, non dimenticherano îl
        ino nome i Corsi, mai. Ricorderanno, o padre, i tuoi sacri
        di
        Cn e Pasquale de Paoli.  U
        ~.
        menti, di. pii, generosi aldannò
        do, ma cogliere di. quelli le
        per adulazione alla Francia, 
        mati potesse avvenire(ma primà
        no) se potesse.. avvenire che. 1
        Corsi dimenticassero,: con Jà
        lingua da te parlata, ? debiti
        ch'hanno alla tua memoria,’ e.
        giudicassero te come un colpevole ; allora la_tua Pairia,o !
        Paoli, sarebbe un ? isola di par
        u [.ve,nn òmu sòlu ha suminatu u graQuelli chi ricevenu AMUManterranno Vantica fama)"
        in Corsica a mezz'a i miò parenti, è
        guastatu, in gran:parte, da: a. tristezza ch’iò risentu a.a vista dia sciagu‘rata situazione:n'a quale jace u miò
        . poveru paese....:.
        fizi, 1 tuoi patimenti, gr esemDI, 1 consigli. Di
        ~ sù = —
        di giusti, di sobrii di contie al pericolo ; SS. riconoscenti;
        forti net domestici affetti,
        spreggiatori del lusso e delle
        grandezie vane, amici incora 
        vutibili della ..civile.. ugua glianza, della. vil. delazione e
        d'ogni atto servile nimici. SapPranno non ss van tare importunamente de' nomi che fanno
        D'isola Toro cospicua né) môns
        lode: Più pure; e in: novelle pros 
        ‘ve, secondo che portali varietà
        inesauribile. de’ tem mpu. emu
        larle... Te 
        spramn' Tesse é fome I~;
        
        Scozia all'Inghilterra -;
        rinnegare la lingua matérnà
        ché da essi non' hà mai pensa
        toa.richiedere tanto,.. e. che sè
        tanto facessero, UH avrebbe: merilamente in disprezzo. Che'se
        il Golo menerà per: acqua nelerécidre:</texte>
        <auteur>Matteu Cirnensi</auteur>
    </rubrique>
    <rubrique>
        <type>infos</type>
        <langue lan="cos">cos</langue>
        <titre>PCA</titre>
        <texte>U Partitu Corsu d'Azione
        ha dicisu di depone, 5 aprile
        chi vene; una palma nàritu a
        {tomba di u. Babbu di À Par
        aspettendu l'òra di a iustizia.
        ria. a u
        À Muovra è incaricata. di
        ricutei fondi necessarii. :
        _ Avisu a l'amici. . Dn
        A sottuscrizione sarà chiusa
        u prima aprile.
        >
        La
        U sicritatiu :</texte>
        <auteur>Dumenicu Massa</auteur>
    </rubrique>
    <rubrique>
        <type>article</type>
        <langue lan="cos">cos</langue>
        <chronique>Riflessioni di un veru corsu</chronique>
        <titre>Leghjte què</titre>
        <texte>- In una € lettera: mandata dà un
        Corsu a'un altru Corsu » parsa IN
        A Muvra di u primu marzu, rilevu
        sti filari :
        «U piacè ch'iò aghiu a ritrovammi
        "> oo Un: tempusi Moitinchi un ? dumani
        davanu d' furesteri manc'u pannu
        Curu quale si véstianu. Granu è al:
        trè biade ci i facianu benissimu ‘e bas: .
        tavanu be. a cunsumazioné locale:
        L "arburi frùttiferi, peri,. meli, noci,
        sorbi, castagni ecc... spendianu frutti
        squisiti cun tale profusione da impie:
        - He ogni casa e permette I ‘allevi di
        ‘numerosi finimali ..
        .-:Oghie-Moita un: è -più quessa. È Li
        'tdèchie kannu invasu u territoriu. 
        Avà, duvé nànzu si i stendianu campi
        'biùndiggienti di biade, vigne magnifiche,verdi giardini, . s'innalzanu ar.bitri e listinchi, scope e filicaghie; ;
        ogni sorta di piante. e di arbuscelli
        -salvatichi.ci ‘prospera in modo spaventevule attestendu a l':rimerchevulé
        fertilità die ferre." + Te
        U tettore -mi Scusifà di stà longa
        cazione. ÆEra: ‘necessaria perche, ciò
        ‘che "l'autore. di à Jettera ‘a dice. di Moi:
        ta, si pò. «di di e- tre perte di: 1 passi
        corsi.
        "Cunoscu * à Moita, à Zalana, tuttu
        u califone di Sera; quelli di Rogna, 
        muntagna,. un c'è nè. padule,. nè zin: 
        quellu. di Boziu; ; sò statu in Pumon«te, , particularmente: in. Coghia;:i in
        Alatà,:in-Coti-Chiavari, : per ‘un :cit- :
        tà che un paese ‘in quà e in là; da
        {per tuttu 'aghiu, intesu u stessu raggiunamentu. U territoriu d'ogni pae:
        ‘sec:éra. prima: un picculu - paradisu
        terrestru, un “pezzi di a’ terra pru- .
        messa da Dio.au populu Ebr eu.Sol:
        Ji. un .ci.n’era, -:ma-roba-un ne man:
        cava: u late eu vinu currianu. pè i
        prati. "Avà "un c'è più nè roba nè
        solli: Ùn c'è che macchie.
        .Ne:i paesi duve si cuntava ottan:
        te pàghj di bòi un ci n'è più ( ca dui
        o tre coppi. Cunoscu un paese in dunu;:: l’acelli n s'hannu: quasi tuttu
        manghiatu.
        guvernu,..a pulitica, i raprisententi :
        Dimune altru è e ‘tantu di cent altri
        Dite piru:cume yi.pare,um'putereJa chè à chi tomba à Corsica ghiè
        . Quale è a à causa di stu tristù -cam,biamentu ? L'avemu detta : u guvernu, i riprisententi e a pulitica! . Ma
        a verità dumanda di pruclamà ch'una
        parte di u nostru maleu duvimu:a noi
        :stéssi.chi,. senza-reagisce,ci lasciemu
        trascinà nantu ..u' stradone chi ci
        porta a l'abissu.  ci:
        Zappate. e suminate : a “robba è cara, è s'avete a roba ‘avete solli! U
        un sò. farina da fanne. ostie;. pudeu .e duveri ianu ajutacci, denduci
        strade megliu che quelle di Moita,
        u mondu che d'aspettà tuttu da un
        guvernu ch'un vòle ,fà nulla.. .; Ripigliemu .a citazione ;
        .«Moita,in menu di dece. anni, hà
        persu. 300 abitanti; un terzu d'a sÒ
        bobllazione SI. n° é _ scappata per sa
        Francia...
        te»
        paesi. E allora ?
        — Allòra 10 
        « Diuvé' si'stendianu campi biun
        déggienti di biade; vigne è giardini,
        :sannalzanu arbi:tri;scope e filicaghie.»
        te-impedimi di gridà naniu a tufti 1
        teiti.e Sopra a tulte e piezze di l'isuU. Junz vunarismu:.. U: funziunarismu è peghiu che a Malaria.:
        In. Moita, cume. in tutti. 1 paesi di
        zale, nè. frebbe... Li
        Prima. -era.: un giardinu "colmu di
        tutti i frutti; dipòi che: i. so abitenti
        Francia, u territoriu di Moita è una
        macchia.... :
        . Cunclusione: .. "Quelli chi preferiscenu l'impiegu a l'aratu, sò liberi ;
        ma quand'elli voltanu n'u. so paese
        e ch'elli; un ci: tròvanu che. macchie,
        ch'elli ficinu un pocu .u so mea cul:
        pa. cn LI
        A pulitica, u.guvernu, Satanassu è
        Subissu mandanu. a. Corsica in ruina, e i Corsi ch'abandonanu. a sô
        terra sì. facenu. i complici di stà
        ruinà. I i</texte>
        <auteur>Sambucucciu di Casinca</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="cos">cos</langue>
        <titre>Lettera da Francia</titre>
        <texte>Cari cumpagni,  
        _— V'avia scrittu. una lettara, duva
        vi parlava d'u u Papa, d'i veschi,
        di l'arciveschi. e di nappone d'Edouard; ma.un aghiu micca avu 
        ti :
        iu u piacere di vedela figurà nanFA Muvra. È. bera. ch'un l'avete
        :mancu ricevuta, sa Lettara, postu
        cha. m'aghiu: tròva in borsa una
        quindecina di jorni, dòpu.-. .Sò cuntentu e mi ne. tengu avà :
        d'un avellavi inviata, ch'o sinnò
        mi ne sarebbe intesu. di un coppiu!
        Figuratevi ch'avià fattu i Stessujornu dui filari in francese per
        zia ‘ntonia-Maria, chi mi manda
        E us  sempre a chere un po Mi tabaccu
        ma sarebbe una scimità tamanta -a
        d prisà. Fece Necessariamente l'addirizzi, e a so letiarà. a missi, poghi mumenti 'dòpu, a'à Posta. E
        laltr'eri quandu, circhendu dui
        mocculi in la miò stacca, truvaia
        vostra lettara, a feci subitu per
        rimettela pulita chi paria avè servitu di basciaculi da tantu ch'ell'era arriguighiulata e brutta.
        Aprendu u fogliu firmai guasi
        acecatu : Intesi cume una manata
        di pevaru in l'occhj. chi si schjaf fonu subiti è a scandillà cume lambichi.
        Chi ghj'era ? Era... chi ghj era
        a lettara per zia 'ntonia-Maària, 
        ch'avia postu TA l'inviluppu di
        A Muvrà. È cusì Face chi d povara
        Zia'ntonià-Maria è stata _obligatà di lascià uso niasone à l'assecCu'— sò 60 :ch’ aghju: prisatu ‘der
        ‘ella e face dinò Chi mi sò inteSù letticà cumè un ladru. Eccu ciò
        ch'ellu si guadagna a vile sérive.
        Zianitônia- Maria, chun sà fà
        mancu un o di culu in la fena,
        m'ha fattu risponde che a miò lettara è d'un veru scioccu è chi nimu un ci ha pudutu capì un strécciu, chì l'ha fatta leghje ùncu a
        ziu Pisticciulu chi leghje purtantu cui specchjetti in oru,ma micca più chè d'altri ùn è pudutu junghje a inturchjà ‘una: Spjgazione.
        Zia ntonia-Marià Mi dice chi
        ghj'è vergugnosa ch'a me'età si
        perdi cusì u ciaffu. «Un sai manCu più scrive in francese: I Tu per
        sa Francia, chi duveriste parlà e
        scrive cume un Pariginu, Diaghj
        invece a cul'indaretu cume i scaravagliuli !... » Fppò, ancu què:
        U miò nasu un ci pensi più ?
        Ah! jé! a vegu bè, hai persu a
        tu sì toccu o malatu,
        dilla e benitine quindi chi gueriscerai...
        Custi Sì ch'ha'nduvinatu,, zi
        ntonia-Maria! Ha ragiò, sò ma
        latu, e medicine per guerimmi un
        ci n'è che d'un genere. Ghj'è à mapatta di u Paese, e un si può QueTi che cu ritornu... °
        Si DO rito Cusì faremu,
        Prima di sucillà a miò lettara,
        tengu a fabbi una ricumandazione, a ciò ch'un b'accadi listessu
        fattu dannificosu che a me: Aprife pianu u Jogliu,ch'ell'un bi scrizgi qualcosa in l'occhj anc'a voi.
        E si tante volte m'accadissi di cumette u listessu sbagliu e chè vo
        un ricevete micca Sta lettara, fatemila sapè chi b’ invieraghju tutt'e
        miò scuse: In tutt'i casi ne ricevefete sempre una nu a lingua nationale (Signore perdunatemi! )
        che sò custrettu di scrive subitu
        avà a Zia ntonia-Maria, chi ghj'è
        anch'ella, senza avè mai postu u
        Pede in bercà, più che infrancisita
        Vi salutu. u</texte>
        <auteur>Petru Borghetti</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>PINCU SCRIVE</titre>
        <texte>A quellu Mertinu chi si n'è andatu a
        appinzà i pali in. Castagniccia.
        U to addio fù bellu, ò Appinzapà,
        L'aghiu lettu, rilettu e studiatu ;
        Ala mente lù sò, pòi tu pensà
        S'ellu mi piace e s'ellu m'ha incantatu.
        T'è dispiacciutu d'avè da chità
        Cume òmu, e pòi più cume curatu,
        Quellu lòcu chi tantu sai lodà
        A capiscu: ma sì ricumpensatu
        Chi tu né si andatu a-u Castellare
        Un lòcu,di a Casinca prelebatu
        A mezza càstagniccia;in faccia au mare..
        Cusfì serai tenutu e. pòi stimatu..
        E si, cume quassù, is sai piglià, ..
        Un perdi nunda per avè cambiatu.
        A sai: ch'iò aghiu avutu. a: disgrazia d'esse mere € chi l'affare dura
        dipòi 21 annu. Si u cartellu di i
        mancini, ellu chi pò fà e disfà,avia
        pensatu di fà i meri in eternu, un
        serebbe statu occupatu appressu a
        -Pelettori, munèta chî bale'ancu menu che u nostru francu.
        Ma u 3 di u mese di 1 sumeri, Si
        deve rifà i cunsigli municipali e pòi
        _ dòpu i merri. E ti diceraghiu ch'iò
        "un dormu più nè notte nè ghiornu,
        _dipòi ch'un certu tanente di a guerra ha apertu a lutta nù u ' miò paese.
        Si Pianellacci eranu cume i Se-j
        nélagesi u tanente l'averébbe fatti
        andà, ancu a calci, duv'elle si principianu _ e. panere; ma a più gran
        perte "sò pastòri senza bisognu e
        " ch'un stanu a sente che u prezzu di
        u latte. Eo sò.u tintennaghiu di tutti è i portu duv'ella ci è l'erba in
        abondanza. Devi capì ch'iò sò tenutu e chi i pastori, oghie, facenu a
        forza nui paesi.. I
        . Averebbe scrittu in prosa e pòi
        _ancu in poesia un pocu più spessu,
        ma ci vole a lascià passà u 3 magbiu. .
        Quist'annu speru. di fà tre belle
        -festé : una u 3 maghiu; una u 12 Maghiu 4 San-Pancraziu di Casinca e
        Valtra u 17 maghiu quandu si feranu i merri — S'iò perdu e feranu
        Y'aversarii. i
        Mi pare di vede ride l'amicu Maistrale quand'ellu leghie st'affari e sen‘tu ch'ellu dice nu a so barba: « Di
        sicuru chi s'ellu un vince, perde. »
        Megliu. ferià di mandami . qualchi
        sollu, ancu puru di quelli. di e so
        alimee, chi seranu ancu più sauriti.
        O Merti sò. statu malatu e pòi
        ci è statu altri intoppi in casa; o
        sinnò mi serebbe fattu vivu prima
        _d'avà. 
        Scusami tu, e tutti i to lettori. di
        a nostra Mufra. S'iò possu mi fera:
        ghiu vivu più spessu.
        Ti salutu,</texte> 
        <auteur>Pincu</auteur>
    </rubrique>
    <rubrique>
        <type>poesie</type>
        <langue lan="cos">cos</langue>
        <titre>EPIGRAMMI</titre>
        <texte>Passa a prucissiò: futtt salutanu :
        Solu Tellè si calfa u sò cappellu...
        Perchè — dumanda u vabbu Sarrajattulu —
        Tettè un saluta ? — Caru u mo zitellu,
        Si Tellè si. scuprissi a chiricuccula,
        . Si vidavia ch'ell'è senza ciarbellu.
        sta
        Echi ha Turcu, u to cane, .
        — Dumanda ziu Pancottu a ziu Juvà —
        Chi appena ch'elle sonanu e campane,
        "Si melte a burulà ?
        Essendu turcu, è contru a riliggione ?
        — Unn'è quessa a raggione, U
        Risponde ziu Juvà : u capiscu u versu
        Di Turcu. Bole dì :
        A scompanà cusì
        Per bestiè cume boi è tèmpu persu.
        sx.
        *
        Parla u maestru : — Alò. dammi una prora,
        O Francisché, chî l'omu è discindente
        Di a scimia. — E in due a trova
        Francischellu a raggiò più cumbincente ?
        Prima ferma cunfusu :
        Eppò, fidiendu in faccia arditamente
        Au sciò maestru, dice : « U vostru musu ! »</texte>
        <auteur>U Babbuziu</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="cos">cos</langue>
        <titre>A GHIASEPPU VIOLA, persu in tarra africana</titre>
        <texte>Caru cugnatu,
        Aghiu lettu cun piacere a lettera
        chi tu m'hai mandatu da si rughioni
        africani. Simu stati cuntenti di sapè
        chi bo a vi scialate tutti.
        In San Petru, malgradu u tempu
        chi bòle fà di e sòie,accettemu tuttu
        (in santa pace e si piglia a muneta
        cum'ella corre. U pane ; si face raris[simu e caru tutti jorni (dui franchi
        u kilo) ma s' impalta cu a farina castagnina — nu miò amicacciu di Pianellu mi ne ha cullatu una sumirata,
        st'etima scorsa, per paga d'una canl zona ch'iò li mandai stu settembre.
        E cusì, cume tu bedi, circheremu ancu noi di campacci sin'a chi.
        Falcina ci permette di tribulà.
        Mi scurdava di ditti chi tutt'e volte chi no mettimu sa paghiôla au.
        fòcu, i zitelli si lettiganu u pulendaghiu — li trovanu forse un gustu
        particulare — ti diceraghju chi a
        bomba sparisce in qualiru e tre sette, si mai ne ferma qualchi fetta, a
        sera i zerbinotti a s'arrustenu nantu
        a ziglia d'u fucone—e ghiè a sòla cosa ch'elli manghianu per scena —
        tante grazie da u Signore ! :
        Mi dici -chi tu buristi cunoscé à situazione pulitica. d'u paese — Ti jùru -ch'iò un ci càpiscu un cavulu ! È
        ogni elettore piatia un partitu sôttu
        pelle — si tu bòlì sapè: qualcosa
        scrivi a Maistrale chi -ti manderà ‘e
        ‘tre canzone ch’ellu bene ‘di: fa (eju
        li n'aghiu cumandatu ùn centu ma
        temu di un-truvà a bendele che dò- {
        pu. l'elezioni) mancanza di quattrini,
        capisci ? E passatu u tempu Ci l'allocazioni ! A partè d'u 3 ‘màghiu
        s'ellu ci fussi qualchi amatore pa
        Yelettori d'u partitu. « si viderà » tandu si principia u néguziu. Si mai un
        ci fussi mezi di spaccialle e mi venderaghiu per tante pisticcine.
        . Ma quale pò. esse u scemu chi t'ha
        dettu ch'iò era candidatu- in SantuPetru? mica. chi l'ambizione un ci
        sia,ma cume sò chi so fiascu un serà
        mai che per mancanza di voti, pre
        feriscud’uti prisentamini nica mi dis[ se ancu u corciu paisanu, cinqu'anni
        I fà (ch'éllu sia alòcu di riposu).
        Ti dicu è ti ripetu ch'in-fatti di
        pàrtitu un'ciinoscu ché quellu ch’ellu preside Petru Rôcca in Aiacciu,
        ou partitu d'a paghiella. Un bedi mi;
        ca chi noi ci vulemu dà per noi tanti
        matàlasci, esse a cultellu tiratu cu i
        nostri vicini quandu i nostri capi
        partiti facenu e disfacenu secondu
        chiu soffiu beñe da foce a tramuntana.
        _ Averebbinu tortu d'un prufitànne
        postu ch'elli sanu chi no simu pron[ti a tutt'ocasione, ancu à legacci :
        l'aghetia.
        Ch'ella vivi a so faccia! U ‘signore ci metti a so "santa
        manu !
        San Petru di Venacu, Marzu 1924.</texte>
        <auteur>Ghiuvanni Olivieri</auteur>
    </rubrique>
    <rubrique>
        <type>revue de presse</type>
        <langue lan="fra">fra</langue>
        <titre>GIURNALI CORSI</titre>
        <texte>Pà
        La nouvelle. Corse — 7-3-25 (At ~
        acciu).
        La Couronne Consnlaire
        Cette couronne a été destinée par la volon_
        té de tous les souscripteurs, à rester perpé.
        tuellement à Ajaccio dans la Maison qui vit
        naître le Grand Homme.
        Il est inadmissible que cette illustre Maison,
        malheureusement si pauvre en meubles et objets napoléoniens, soit encore dépouillée de
        lement par tout le peuple ajaccien, sans distinction de partis, -en une journée d'émouvant
        enthousiasme qui reste une date de l'histoire
        locale de notre ville.
        Comme Ajaccien, comme souscripteur moimême et en souvenir de mon père qui fot -le promoteur de la souscription et de la commémoration du Cenfenaire du Consulat a Ajaccio,
        je viens protester énergiquement contre le
        projet d'envoyer la couronne à Paris, dans un
        musée, où elle~serait confondue parmi tant d'autres objets d'art et pèrdrait toute le signification dela pensée qui présida à la souscription.
        E. Forcioli-Conti.
        L'Observateur — 9-3-25. (Bastia)
        =: Cose andate par J. P.Lucciardi.
        
        
        Parler ‘de nos s poètes corses, est un à plaisir
        de passer 'avec eux, par üne gamme ‘de sentiments tôur à tour émouvants, passionnants, tou.
        éhons à leur livre : comme l’alouette: aù miroir.
        lecteur bien évocateur. Andate, passéés, révovre un horizon îllimité. - -~
        De ces choses, si chères à nos ancêtres piuss s0bres que nous ne le sommes, que. reste-t-il, si
        non un lointain souvenir ! 1 Ce souvenir; le poète attaché, à nous le rappeler. Que Voilà ùn beau.
        sujet, quoique rustique, ‘pour un poète. aussi
        fervent qué Pést Lucciardi, dè toutes Dos vé
        .nérables'et tôuichantes coutumes. : ©": "*
        Ce beau recueil se.présente à nous, sous une
        belle couverture, èlégante et sérieuse à Ja fois,
        ble. Comme de juste, ce volume nons vient.dè [
        l'imprimerie- de A Muvra, qui ne chôme j jamais:
        Une préface en. vers, due à Brandone, ouvre lè
        recueil. Brandone, nous dit son amour des Co 
        se andate et sà ‘crainte de nous voir  éublièr le 
        glôriéux passé ‘de nos ‘ancêtres dans, ‘sa poi
        'gnanté ‘épître liminaire. a
        . Sachons donc, ainsi: qu’il nous le proposé 
        sM.
        ainsi que des reliques
        _ A lumera, A deda, A Rocca, U ‘pilone, Ü Fornu etc. .; telles sonf les Cose Andate que. ‘chanet qui: nous font revivre -des: temps: révolns.
        Tout dans ‘ce volu, à le classique accent de
        la perfection. .
        : Le lecteur sera frappé, par la. vérité du ta:
        bleau, la. conduite de l'action, la composition I
        de ces petites scènés ‘auxquelles ‘donnent lieu
        les plaintes des Cose 'andàte, le bonheur des
        lequel le poète nous entretient de ces humbles
        Lisez Corses, lisez ces différentes poésies qui
        sont comme des hymhes; écrits à là gloire de.
        Cyrnos notre vieille patrie, et peut être:y troumaux dont nous souffrons. UT
        Matteo Ciriiénsi.
        L'Eveil de cla Corse — —. I0- 0325 (Aio
        acciu)... .
        . D est une œuvre cependant q qui devrait être
        placée dans l'ordre des. réalisasions, au: rang
        qu'elle tient dans les; conditions économiques 
        
        piè Cn 2 “E fatti un segnu di croci !"
        
        de l'île, l'an des tout, premiers : C’est. celle de
        l'irrigation: Le manqué d’eau est l’un des plus.
        'grands maux. dont souffre la Corse.Le : manque ;
        d'eau est, pour le Sol, ce que’lé paludisme
        est pour les persones, ‘une cause.  d'anémie et
        de mort.
        Sans l’eau d'irrigation, nulle "cultute ne se
        développe, ni les arbres ni les pâturages. La
        Corse se stérilise par suite de la sécheresse.
        Et l'on-ne devrait songer'à l'ônuverture d'aucu-ne route, nationale, vicinale ou rurale, tant
        que les eaux de nos torrents portent à la mer
        leurs eaux précieuses, sans avoir été utilisées
        sur leur passagé. IP. è</texte>
        <auteur>Inconnu</auteur>
    </rubrique> 
    <rubrique>
        <type>revue de presse</type>
        <langue lan="cos">cos</langue>
        <titre>GIURNALI CORSI</titre>
        <texte>La Corse — 8-3-25 (Marseglia), E
        Saugni Corsir I
        
        A î milli di Caillauz,
        A i milli di Millerand,
        A i milli di Monmouseau.
        
        U sangui ba corsu in a stretta
        Ista -mani... _
        Taglia al arbitra una vetta
        È fattî un ségnu di croci !
        - Sangui Corsu.
        Ti n’andesti gocci a gocci !
        Era cusì puru u celi,
        _ F'macchioni
        Eranu pieni ad accelli,
        U celi era cusì puru,
        Zittu e piattu
        C'era un òmu a u ped'd'un muruFronti bassu e visu strann,
        O figldli,
        Avia un fucile in manu.
        Un ajiîti pur paure,
        O acelli
        Chi di voi un'ha primura.
        
        
        *_ « —U sole t'ha imbriagatu ?
        O di tè
        Cristu s'è diminticatu ?
        A ciò chi tu facci abbada ! »
        Da qua'njò
        _ Colla un òmu a mezza biada !
        Zifulendu e spenseratu...
        cn  Guai e guai!
        : : « Volta, volta, ò disgraziatu !
        Ma sempre, lestru, ellu marchia,
        E la morti
        L' aspetta piatta i in a macchia. 54
        Un accendita ! Un brionu !
        ' Unu cascà __
        L'altru fughi in u macéhionu !" 
        Ela biada gluriosa Louer
        Tutta d'oru Oramai è sanguinosa. è
        U sangui a corsu in a stretta
        {sta mani
        Taglia a l'arbitru una vetta
        
        Sangui corsu
        Ti n'andesti gocci a gocci !
        Carlu GIOVANI.</texte>
        <auteur>Inconnu</auteur>
    </rubrique>
    <rubrique>
        <type>revue de presse</type>
        <langue lan="fra">fra</langue>
        <titre>ALTRI JURNALI</titre>
        <texte>Action Française eee MI
        Là où il eùt fallu des s bommes, la "Rrancé
        d ~ Millerand, : ùn
        gure. est. un, trait commun aux républicains,
        qu'ils sortent du. ruisseau, comme Briand,
        ou ‘de l'Ecole dè droit, comme: - Millerand :
        et “Poincaré. J'en suis, comme disait. _ Mme
        Sévigné, frappé an delà de la-raison.-.La
        Convention, qui fut terrible, avait ‘du moins'le
        -$éns: de la ' grandeur, joint: à celui de: la
        réalité: pressante. Vous chercheriez. en .
        vain ce sentiment, dans les! assembléés,
        eritre 4949 et 1925. -N a ‘été remplacé par
        le peur, . ou. plutôt, "ce: terme étant trop noble, par. la frousse.
        . Eclair. de Montpellier  
        “Pourquoi conserve-t-on leurs lonctions ‘eu :
        Préfet Marlier, aux policiers. Delange, Lannés
        et Colombo, contre qui,. par l'ordonnance du
        premier - président ‘de-la: cour d'appel de Pa:
        ; ris; "une “information-est ouverte: -pour- -homicide volontaire, détournement de mineur et complicité ? Cés quatre hauts personnages ne sont
        ‘que des prévénus, maîs ils sont des prévenùs. [
        Comment peut-on leur converser des fonctions 
        _qui leur permettent, après avoir comparu de‘vent des juges pour ètre interrogés éteonfron_tés: comme: prévenus, de revenir devant eux. c
        comme leurs collaborateurs _et leurs auxiliai‘res ? Comment péut-om leur conserver des
        fonctions qui' laissent. à' leur. discrétion ‘des 
        rouages et des moyens, une influence dontils
        peuvent être tentés de se, servir pour, dérouter la justice. - si vi
        ; -Et le préfet Marlier:? Tout -ce que. NOUS - venons de dire s 'applique à lui, en raison des
        "fonctions qu'il occupait lorsque Philippe Daudet a'été tué; qu'il n’occupé plus sans douté,
        .mais-qui ont dù lui laisser une certaine int 
        'ènce. Enfin, il est: préfet, - d'un département,
        -la Gorse;:et on ne:sauraît admettre qu'un pré i
        fet-inculpé, .d'homiside . volontaire. ou de com plicité, puisse demeurer préfet tant qu'il reste.
        inculpé Si cette situation persistait, le magui, .$e viderait, ceux qui le tiennent encore com.
        prenant qu'une ère nouvelle est venue et qu à [
        penvent  désormais tenir Ie haùt da pavé.</texte>
        <auteur>Inconnu</auteur>
    </rubrique>
    <rubrique>
        <type>lettre</type>
        <langue lan="cos">cos</langue>
        <titre>Una lettara</titre>
        <texte>Tagliu, u 12 ferraghiu 1925
        Caru cumpagnu di fede,
        Eccumi rientratu in Tagliu. Ci aghiu
        tròvu itre numeri di A Muvra; un pude,
        te crede quantu piacè aghiu avutu a je
        ghiele, se care muvrarelle salvatiche e